### ISSUE TITLE
Move logging framework from logger to slf4j

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs-java#10]
_From @SreeramGarlapati on May 16, 2016 17:1_

One open Item here is - if the log4j appender has to push events to EventHubs using the JavaClient - how to ignore the eventhub events (am sure there should be a way)

_Copied from original issue: Azure/azure-event-hubs#148_

**Comment by SreeramGarlapati** [comment]
Mapping for SLF4J trace levels:
Trace - delivery id (message level logs)
debug - flow control, delivery/message decode failures, token logs
info - positive connection/link activity, token failures, close link failures etc
warn - failures at link level, connection level, client-entity, reactor-dispatcher-errors
