### ISSUE TITLE
Can't read events from EventHub when using 0.13.1 release

### ISSUE THREAD

**Issue by sergaz-msft** [Azure/azure-event-hubs-java#100]
Release 0.13.1 is not returning anything (nor even an error message) when you try to read from the Event Hub (normal EventHub or IoTHub EventHub). If you roll back to 0.13.0 all works as expected.

Using the sample from here: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-java-java-getstarted#receive-device-to-cloud-messages

**Comment by jonathan-macke** [comment]
The same for me with release 0.14.0. Must stay with the release 0.13.0

**Comment by SreeramGarlapati** [comment]
hi @sergaz-msft / @jonathan-macke - can you please tell if
- this java pom where you are reading from, include IOT libraries as well ? We saw very similar issues in the past when conflicting versions of Proton-j dependencies were used.. If so, can you please update the IOT hub libraries and EPH to have matching proton-j dependencies..

**Comment by dominicbetts** [comment]
I'm seeing the same issue - release 0.13.0 is the last one that works with the IoT Hub Event Hub-compatible endpoint. The dependencies in the POM are:
```xml
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
          <groupId>com.microsoft.azure</groupId>
          <artifactId>azure-eventhubs</artifactId>
          <version>0.13.0</version>
    </dependency>
  </dependencies>
```

If you change 0.13.0 to 0.13.1 the code stops working - no exceptions, just nothing read from the endpoint.

**Comment by SreeramGarlapati** [comment]
@sergaz-msft, @jonathan-macke , @dominicbetts - we fixed this in a recent PR. pls. verify and let us know if it works... as expected.
