### ISSUE TITLE
MessageFactory throws NPE: java.lang.NullPointerException: uncorrelated channel: 0

### ISSUE THREAD

**Issue by joearkay** [Azure/azure-event-hubs-java#103]
## Versions  
- Raspbian on Raspberry Pi 
- Maven package version or commit ID: 0.11.0

NPE thrown by the library. My implementation is nothing more complex than what is detailed[ here](https://github.com/Azure/azure-event-hubs-java), although I actually close the ehSender, which the doc seems to miss out.

Pasted below is the error message: 

`Apr 21, 2017 3:34:39 AM com.microsoft.azure.servicebus.MessagingFactory$RunReactor run
WARNING: UnHandled exception while processing events in reactor:
java.lang.NullPointerException: uncorrelated channel: 0
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:310)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:278)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:414)
java.lang.Thread.run(Thread.java:745)Cause: uncorrelated channel: 0
org.apache.qpid.proton.engine.impl.TransportImpl.handleBegin(TransportImpl.java:1128)
org.apache.qpid.proton.engine.impl.TransportImpl.handleBegin(TransportImpl.java:66)
org.apache.qpid.proton.amqp.transport.Begin.invoke(Begin.java:144)
org.apache.qpid.proton.engine.impl.TransportImpl.handleFrame(TransportImpl.java:1367)
org.apache.qpid.proton.engine.impl.FrameParser.input(FrameParser.java:418)
org.apache.qpid.proton.engine.impl.FrameParser.process(FrameParser.java:527)
org.apache.qpid.proton.engine.impl.SaslImpl$SaslTransportWrapper.reallyProcessInput(SaslImpl.java:651)
org.apache.qpid.proton.engine.impl.SaslImpl$SaslTransportWrapper.process(SaslImpl.java:600)
org.apache.qpid.proton.engine.impl.HandshakeSniffingTransportWrapper.process(HandshakeSniffingTransportWrapper.java:101)
org.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.unwrapInput(SimpleSslTransportWrapper.java:135)
org.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.process(SimpleSslTransportWrapper.java:361)
org.apache.qpid.proton.engine.impl.ssl.SslImpl$UnsecureClientAwareTransportWrapper.process(SslImpl.java:144)
org.apache.qpid.proton.engine.impl.TransportImpl.process(TransportImpl.java:1478)
org.apache.qpid.proton.reactor.impl.IOHandler$1.run(IOHandler.java:226)
org.apache.qpid.proton.reactor.impl.SelectableImpl.readable(SelectableImpl.java:118)
org.apache.qpid.proton.reactor.impl.IOHandler.handleQuiesced(IOHandler.java:62)
org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:382)
org.apache.qpid.proton.engine.BaseHandler.onReactorQuiesced(BaseHandler.java:87)
org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:206)
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:310)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:278)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:414)
java.lang.Thread.run(Thread.java:745)`

**Comment by SreeramGarlapati** [comment]
Hello @joearkay - can you please try on our latest client and see if this repro's?

**Comment by SreeramGarlapati** [comment]
@joearkay - we fixed an issue which has the exact same stacktrace. I am unsure how to get a raspberry pi stack up and running.. appreciate if you can validate this with our latest version `0.14.2`...

**Comment by sjkwak** [comment]
@joearkay - we believe this issue was fixed. Please reopen it if it still happens.
