### ISSUE TITLE
Doc autogenerated for _partition_receiver.receive has unformatted code sample in top-level description

### ISSUE THREAD

**Issue by erickson-doug** [Azure/azure-event-hubs-java#106]
## Actual Behavior
1.  https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.eventhubs._partition_receiver.receive#com_microsoft_azure_eventhubs__partition_receiver_receive_final_int_ -- there is unformatted sample code in the top-level description.

## Expected Behavior
1. No unformatted sample code in the top-level description.
2. Formatted sample code (implemented as an overwrite) in the body of the doc page.

Dev should move code sample to documentation -- work with APEX Event Hubs content writer to implement as overwrite.

## Versions  
- OS platform and version: 
- Maven package version or commit ID:

**Comment by sethmanheim** [comment]
@jtaubensee @erickson-doug Can't this be fixed in the source?

**Comment by sethmanheim** [comment]
@sjkwak @jtaubensee Would be good to fix in source, in the meantime PR for the overwrite is #130.
