### ISSUE TITLE
Unnecessary rebalancing of partitions

### ISSUE THREAD

**Issue by adoelger** [Azure/azure-event-hubs-java#115]
## Actual Behavior
1. We have an EventHub with 10 partitions.
2. We have 2 VMs with EventProcessorHosts
3. After starting the 2 EventProcessorHost instances a load balancing starts and each instance consumes 5 partitons. So far so good!
4. At least once in an hour we see a rebalancing of partitions. There is no obvious reason for a rebalancing.
5. After activating the logs of EventProcessorHost it seems that the renew of a lease (Azure Blob Storage) some times take longer than 30 seconds. So the leases expire and the second one takes over the partitions. After a short period of time a rebalancing occurs and the first one acquires 5 partitions back.
6. The continous rebalancing of partitions leads to a lot of reprocessing of messages that are not 
 yet checkpointed. Also the amount of threads starts to increase after multiple rebalancings (see https://github.com/Azure/azure-event-hubs-java/issues/113).

## Expected Behavior
1. Maybe "leaseDurationInSeconds" should be configurable?
2. Set a Timeout on Azure Blob Storage calls and make a retry if timeout occurs.

## Versions  
- Linux:
- Maven package version : 0.14.0

**Comment by SreeramGarlapati** [comment]
this is a good one - thanks @adoelger for providing the debug info - that helped - we are working on it.

**Comment by SreeramGarlapati** [comment]
@adoelger - we addressed this issue in #122. This is released to mvn central as part of `0.14.2`. We exposed the leaseDuration and leaseTimeout to users so that they are more tunable to the needs.

we have one more improvement related to this one - pending - which is tracked as part of #134

**Comment by adoelger** [comment]
Currently the problem could only be solved with a hack. 
See the code from release 0.14.4:

Class: **PartitionManagerOptions**
```
/**
 * The default duration after which a partition lease will expire unless renewed.
 */ 
public final static int DefaultLeaseDurationInSeconds = 30;
...
protected int leaseDurationInSeconds = PartitionManagerOptions.DefaultLeaseDurationInSeconds;
```
Class: **AzureStorageCheckpointLeaseManager**
```
private Boolean acquireLeaseSync(AzureBlobLease lease) throws Exception
{
  ...
  newToken = leaseBlob.acquireLease(this.host.getPartitionManagerOptions().getLeaseDurationInSeconds(), newLeaseId);
  ...
}
```
So far so good , `leaseDurationInSeconds` is used to acuire a lease for the specfied amount of time. But in the same class `leaseDurationInSeconds` is also used to initialize the maximum execution time of the lease operation! 
```
void initialize(EventProcessorHost host) throws InvalidKeyException, URISyntaxException, StorageException
{
  ...
  this.leaseOperationOptions.setMaximumExecutionTimeInMs(host.getPartitionManagerOptions().getLeaseDurationInSeconds() * 1000);
  ...
  this.renewRequestOptions.setMaximumExecutionTimeInMs(host.getPartitionManagerOptions().getLeaseDurationInSeconds() * 1000);

  ...
}
```
That means if there is a problem aquiring the lease (we get a TimeoutExeception) the lease is always expired and probably a rebalancing will occur.
We should have two configutation values `leaseDurationInSeconds` and for example `leaseOperationTimeoutInSeconds`.  

Currently I have implemented the following hack:
```
host.getPartitionManagerOptions().setLeaseDurationInSeconds( 10 );
host.registerEventProcessor( eventProcessorClass, options ).get();
host.getPartitionManagerOptions().setLeaseDurationInSeconds( 30 );
```
Which results in the maximum execution timeout for the lease operation is 10s and the lease will be acuired for 30s. If there is a problem renewing the lease there will be a timeout after 10s leaving enough time to retry the operation.

**Comment by JamesBirdsall** [comment]
Please take a look at branch javaTimeKnob -- I have added an option that lets you adjust the storage timeout for lease operations. Does this meet your needs?

That said, please use caution when adjusting this and other timing values. There are multiple conflicting considerations. As you say, it makes sense for the storage timeout to be shorter than the lease duration, but we have heard about storage latency issues from plenty of customers, and adjusting the timeout to be too short can leave you in a position where storage operations always timeout and EPH is nonfunctional -- or it may work fine now and then end up in that situation later if storage latencies go up. You could increase the lease duration instead, but there's a max of 60 seconds (which is out of our control) and the longer the duration, the less responsive EPH is when nodes fail or are removed.
