### ISSUE TITLE
Request to create Event Hub Client using existing Shared Access Signature token

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs-java#12]
_From @jbrodeur on April 19, 2016 21:22_

JAVA - Event Hub Client Example:

final String namespaceName = "----ServiceBusNamespaceName-----";
final String eventHubName = "----EventHubName-----";
**final String sasToken = "-----SharedAccessSignature token-----";** // A previously issued Shared Access Signature token

ConnectionStringBuilder connStr = new ConnectionStringBuilder(namespaceName, eventHubName, **sasToken**);

EventHubClient ehClient = EventHubClient.createFromConnectionString(connStr.toString()).get();

_Copied from original issue: Azure/azure-event-hubs#119_

**Comment by jtaubensee** [comment]
_From @SreeramGarlapati on April 20, 2016 16:17_

Thanks @jbrodeur for suggesting the feature. We are working on it. Will update - as soon as I have an ETA.

**Comment by jtaubensee** [comment]
_From @SreeramGarlapati on August 9, 2016 5:50_

#15

**Comment by sjkwak** [comment]
This is fixed by #31 - SAS token support.
