### ISSUE TITLE
No offset or sequence number when receiving based on Instant

### ISSUE THREAD

**Issue by pycloux** [Azure/azure-event-hubs-java#123]
## Actual Behavior
1. Creating a PartitionReceiver using the "create​Receiver​Sync(final ​String consumer​Group​Name, final ​String partition​Id, final ​Instant date​Time)" method
2. Read some events
3. The EventData objects offset and sequence number (receivedEvent.getSystemProperties().getSequenceNumber() and receivedEvent.getSystemProperties().getOffset()) are equals to "0"

## Expected Behavior
The EventData should have a valid "offset" and "sequenceNumber".

## Versions  
- OS platform and version:
Centos7 / Java
- Maven package version or commit ID:
0.14.0

**Comment by SreeramGarlapati** [comment]
does this happen consistently ? can you paste repro code here..

**Comment by pycloux** [comment]
Hi Sreeram,
I have run again my code this morning and I am not getting these 0 offset & sequence messages.
I tried multiple times and the behaviour seems consistent, so I assume this is not related to the client.
Best regards,
PYC
