### ISSUE TITLE
Closing parent entities should close child entities

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs-java#13]
_From @hmlam on February 19, 2016 21:6_

E.g. closing EventHubClient should close all the PartitionReceivers created from that instance.

_Copied from original issue: Azure/azure-event-hubs#53_

**Comment by SreeramGarlapati** [comment]
current behavior is that we don't close the child entities automatically - when parent entities are closed. use something like:
`partitionSender.close.whenComplete((void, exp) -> ehClient.closeSync()).get();
'
to make sure parent entities are set to closed state - even when child entities close call failed.

**Comment by SreeramGarlapati** [comment]
This issue was about closing innerSender instance or EventHubClient & was addressed over several PRs (like #199) - which is complete now.
