### ISSUE TITLE
Double counting outgoing messages

### ISSUE THREAD

**Issue by pycloux** [Azure/azure-event-hubs-java#132]
## Actual Behavior
1. Create a brand new event hub
2. Send 50 messages in a hub
3. Read the messages (using sync methods with a PartitionReceiver).
50 messages are received.
4. Logging on the azure portal, number of outgoing messages is 100 (exactly the double).
[RetryPolicy on the client is forced to no retry which I guess is the default anyway, no exceptions, nothing special]

## Expected Behavior
The Azure console should display the exact same number of messages as the one received.

## Versions  
- OS platform and version: CentOs / Java 1.8
- Maven package version or commit ID: 0.14.0

**Comment by SreeramGarlapati** [comment]
@pycloux - thanks a lot for filing this issue.
This is a bug on our service metrics pipeline and we are fixing it... will keep you posted with our release...

**Comment by SreeramGarlapati** [comment]
@pycloux - this is fixed now. We moved the old counter to OutMessages(deprecated)
![image](https://user-images.githubusercontent.com/11813428/28229241-d2aadaba-6896-11e7-9589-0d322d9ab202.png)

(Please feel free to reopen if you don't see it in Command line. I verified this on Portal - which pretty much reads from the same source as the Command line)
