### ISSUE TITLE
Creating the PartitionReceiver without calling for any receiveSync download the messages anyway

### ISSUE THREAD

**Issue by pycloux** [Azure/azure-event-hubs-java#133]
## Actual Behavior
1. Creating a PartitionReceiver using the createReceiverSync of an EHClient
2. No call to receiveSync
3. On the azure console, the outgoing messages is not null and actually reflect a count of messages with is matching with what is in the queue

## Expected Behavior
1. Ougoing messages shoud be 0

I know that there is a "prefetch" parameter for the PartitionReceiver but it is not part of the constructor.
Thus we would normally assume that it is not used until we call "receiveSync".

## Versions  
- OS platform and version: CentOS / Java 1.0
- Maven package version or commit ID: 0.14.0

**Comment by SreeramGarlapati** [comment]
Imagine, EventHubs as a Stream data structure on Cloud, and by the nature of the stream semantics, we are primarily geared towards designing for prefetch/low-latency scenarios. This is an expected behavior.!

**Comment by pycloux** [comment]
Yes I understood but since there is a parameter to set the pre-fetch policy, I was expecting it to be applied once the "receive" is called and not before.
I would recommend to make it clear in the class documentation.
