### ISSUE TITLE
EPH: IO timeouts on 1 partition shouldnot lead other partitions to loose Leases 

### ISSUE THREAD

**Issue by SreeramGarlapati** [Azure/azure-event-hubs-java#134]
with the current design of `PartitionManager` - for ex: if an EPH instance is hosting 4 partitions and the first 2 partitions encounter `StorageTimeoutException` while renewing leases - the next 2 partitions would have lost their lease - as they failed to `renewLease`.
This is because - renew leases is happening sequentially - **where as it should actually be happening in parallel - for all partitions.**

**Comment by yuimam** [comment]
@SreeramGarlapati 
@JamesBirdsall 
My customer hopes for this feature to be implemented.
Do you have a plan to release this in near version?

**Comment by sjkwak** [comment]
Hi @yuimam, we're going to work on the feature in several weeks and we will update this thread as we make progress.

**Comment by ToshinaoOnodera** [comment]
@SreeramGarlapati
@JamesBirdsall
Hello,
Our customer wants to make sure whether we can already use fixed modules or not. Could you please share the current status of this issue? If this feature isn't implemented, do you have any ETA on this work?

**Comment by JamesBirdsall** [comment]
The code is in testing now. Because this is a significant change, we would like to test it thoroughly, so it will still be a while before release, but we are working on this issue and making progress.

**Comment by JamesBirdsall** [comment]
These changes were merged in PR#202, which became part of the 1.0 release.
