### ISSUE TITLE
Client should support TokenProvider model

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs-java#15]
_From @hmlam on January 26, 2016 19:20_

Just like the .Net counter part, we should have some form of TokenProvider model to support
1. token generation from key so that we can use token across the wire protocol instead of key
2. renewal/re-generations of tokens

_Copied from original issue: Azure/azure-event-hubs#15_

**Comment by jtaubensee** [comment]
_From @sjkwak on September 2, 2016 18:54_

We will address this with issue #119.

**Comment by SreeramGarlapati** [comment]
#28 implements token based authorization.

**Comment by sjkwak** [comment]
#31 implements SAS token support.
