### ISSUE TITLE
Activating of SSL or SSL over AMPQ

### ISSUE THREAD

**Issue by pycloux** [Azure/azure-event-hubs-java#159]
Hi,

We want to activate SSL for securing the transport of the messages.
I looked at the class https://github.com/Azure/azure-event-hubs-java/blob/dev/azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/ConnectionStringBuilder.java

It seems that AMPQS is the default:
```
final static String endpointFormat = "amqps://%s.servicebus.windows.net";
final static String endpointRawFormat = "amqps://%s";
```

Please can you confirm that the library is using AMPQ over SSL by default ?

Best regards,

PYC

**Comment by SreeramGarlapati** [comment]
Yes @pycloux - it is amqps by default.
However, remote-peername identification support is yet to be added.

**Comment by SreeramGarlapati** [comment]
(sorry, clicked on 'close and comment' instead of comment button by mistake).

**Comment by pycloux** [comment]
Thanks for the answer.
