### ISSUE TITLE
Consider moving InMemoryCheckpointManager to main source tree

### ISSUE THREAD

**Issue by adriancole** [Azure/azure-event-hubs-java#162]
Perhaps in a testing package, [InMemoryCheckpointManager](https://github.com/Azure/azure-event-hubs-java/blob/75ce065872ed0cf4425b0fd5e931cec5d2d049c2/azure-eventhubs-eph/src/test/java/com/microsoft/azure/eventprocessorhost/InMemoryCheckpointManager.java) should be in the main source tree. This simplifies people testing setups as they don't need to supply a storage account. This would make zipkin demos easier for example.

cc @aliostad

**Comment by aliostad** [comment]
Hi, sorry, will get back to you.

**Comment by SreeramGarlapati** [comment]
#194 addresses this ask.

**Comment by SreeramGarlapati** [comment]
(@adriancole - closing this as the PR went in and we are releasing the bits. Milestone wouldn't show as completed until the linked issues are all closed. pls. feel free to open if you have any feedback specific to this ask).

**Comment by adriancole** [comment]
cheers. thanks for following up!
