### ISSUE TITLE
Make library mockable

### ISSUE THREAD

**Issue by yarinm** [Azure/azure-event-hubs-java#169]
At the moment, it's really hard to test the code using this library because many classes are marked as internal and final.

It can be really simple to have this library mockable if IEventHubClient interface would use 
IPartitionSender and IPartitionReceiver instead of concrete implementations.

At the moment it's impossible to easily mock this library.

What do you guys think?

**Comment by yarinm** [comment]
ClientEntity::getIsClosed should be public. It's funny that I can't check if an object is already closed.

I know that IllegalStateException is raised if a closed object is being used but we should be able to check for it before trying to use the object.

**Comment by sabeegrewal** [comment]
Hey yarinm, I'm happy to get to this, but, if you'd like, you're welcome to create interfaces for classes you'd like to mock and update the ClientEntity::getIsClosed access. Just open a PR and someone will review and merge it in :) 

If not, I'll get to this in a little bit! Thanks!

**Comment by SreeramGarlapati** [comment]
addressed in #244
