### ISSUE TITLE
How to find out if a consumer group exists?

### ISSUE THREAD

**Issue by greendale1924** [Azure/azure-event-hubs-java#172]
Hi.
Short story: I want to check if a consumer group exists for a given hub. I don't want to start the EventProcessorHost if the group does not exist. So, what is the easiest way to verify the consumer group?

Long story: The EventProcessorHost does not care if the consumer group exists. It creates the instances of IEventProcessor (one per partition). Then, IEventProcessor.onOpen and IEventProcessor.onError are called again and again (maybe forever?). I don't see any reason for all this, thus I want to avoid it. What I need is a fast feedback that something is very wrong with the configuration of the application.

**Comment by SreeramGarlapati** [comment]
I would do a simple rest call before starting up `EPH`, here's our rest API for GetConsumerGroup: https://msdn.microsoft.com/en-us/library/azure/mt652143.aspx

**Comment by JamesBirdsall** [comment]
Using REST is currently the best solution. We are aware of the larger issue of EPH spinning even when there is no hope of success and I have opened issue 291 to address it generally.

**Comment by warrenzhu25** [comment]
You can use azure management java sdk to get the namespace. But currently, it has some bug. See #332
