### ISSUE TITLE
Why does the event processor host not open connection partition 0 and 1 of "$Default" consumer group?

### ISSUE THREAD

**Issue by meomeo0110** [Azure/azure-event-hubs-java#185]
Hi all;

I created a eventhub entity with 8 partition and 2 consumer group: "$Default" and "other".
Setup 2 processor host with different name and different consumer group as below:

` EventProcessorHost host = new EventProcessorHost("host", eventHubName, "$Default", eventHubConnectionString.toString(), storageConnectionString, storageContainer);
        EventProcessorHost host2 = new EventProcessorHost("host2", eventHubName, "other", eventHubConnectionString.toString(), storageConnectionString, storageContainer);`

And IEvenProcessor implement:
` public void onOpen(PartitionContext partitionContext) throws Exception {
        System.out.println("Open partition: " + partitionContext.getPartitionId() + " .Owner: " + partitionContext.getOwner());
    }`
The host that use "$Default" consumer group only print: "Open partition x. Owner: host". x is 2 from 7, while the host that use "other" consumer group  print all partition: 0 --> 7.
Later, i use another consumer group named: "other2", all partition is listed.
It seems the situation only happen on "$Default" consumer group?

## Actual Behavior
1.  "$Default" open connection of partition:  2->7 only

## Expected Behavior
1. "$Default" open connection of partition:  0->7

## Versions  
- OS platform and version: Window 10
- Event hub eph: 0.14.4

Thanks you

**Comment by JamesBirdsall** [comment]
There's nothing special about $Default as far as partitions go: if there are eight partitions, then all eight should open. Do you have error notifications hooked up? Did you get any exceptions?

**Comment by meomeo0110** [comment]
Sorry, I don't know why, today the event processor host is able to open a connection to partition 0 and 1.
Yesterday, not only my machine meet this problem.
I will check it again in tomorrow.
