### ISSUE TITLE
unregisterEventProcessor method execution takes too long (version 0.15.1)

### ISSUE THREAD

**Issue by vinipuh5** [Azure/azure-event-hubs-java#200]
unregisterEventProcessor takes too long in version 0.15.1 by comparing to 0.13.1.  

## Actual Behavior
1. unregisterEventProcessor execution takes about 60 - 90 seconds for event hub with two partitions.

## Expected Behavior
1.  The execution takes few seconds like in version 0.13.1

## Versions  
-  azure-eventhubs-eph:0.15.1

**Comment by vinipuh5** [comment]
I did some extra check and found that unregisterEventProcessor works fine up to 0.14.2 (including)

**Comment by JamesBirdsall** [comment]
Have you tried the recently-released 1.0 version? It is substantially different inside. So far we have not observed slow shutdown.

**Comment by sjkwak** [comment]
We've made several improvements in the scenario and we believe the issue was fixed. Please reopen the issue if the issue still occurs.
