### ISSUE TITLE
uncorrelated channel

### ISSUE THREAD

**Issue by tcbjc** [Azure/azure-event-hubs-java#204]
## Actual Behavior
1. When Web Site Log send data to EventHub, Tomcat Log show lot of uncorrelated channel: 0.
2. 

## Expected Behavior
1. 
2. 

## Versions  
- OS platform and version: Centos
- Maven package version or commit ID: 0.14.4

Pasted below is the error message:
15-Nov-2017 19:46:00.287 WARNING [163988628] com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run UnHandled exception while processing events in reactor:
java.lang.NullPointerException: uncorrelated channel: 0
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:277)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:381)
java.lang.Thread.run(Thread.java:748)Cause: uncorrelated channel: 0
org.apache.qpid.proton.engine.impl.TransportImpl.handleBegin(TransportImpl.java:1132)
org.apache.qpid.proton.engine.impl.TransportImpl.handleBegin(TransportImpl.java:66)
org.apache.qpid.proton.amqp.transport.Begin.invoke(Begin.java:144)
org.apache.qpid.proton.engine.impl.TransportImpl.handleFrame(TransportImpl.java:1373)
org.apache.qpid.proton.engine.impl.FrameParser.input(FrameParser.java:418)
org.apache.qpid.proton.engine.impl.FrameParser.process(FrameParser.java:527)
org.apache.qpid.proton.engine.impl.SaslImpl$SaslTransportWrapper.reallyProcessInput(SaslImpl.java:652)

**Comment by SreeramGarlapati** [comment]
Hi @tcbjc  - do you see this with our latest version `0.15.1`.
Is there a sample of sequence of steps that we can try to reproduce this error...
Did you happen to collect warn level logs for javaclient - which would help a lot..?

**Comment by SreeramGarlapati** [comment]
Hi @tcbjc - you mentioned website log - can you please explain us - where you hit this. We are trying to release `1.0.0` very soon & would really like to address this in that release...

**Comment by SreeramGarlapati** [comment]
@tcbjc - please reopen if you hit this with our latest version.

**Comment by dgilling** [comment]
We are seeing this in 1.0.0. Filed under #287
