### ISSUE TITLE
EPH: Logging is cumbersome

### ISSUE THREAD

**Issue by szymansh** [Azure/azure-event-hubs-java#205]
The Event Processor Host library is constantly outputting messages as the leases are updated for the partitions.  These messages only provide value when debugging a problem and should typically be suppressed to not flood the log.  Can these messages be changed to the debug level instead of info level?  The user can already log when partitions are opening and closing when they implement the IEventProcessor.

## Versions  
- OS platform and version: CentOS 7.2
- Maven package version or commit ID: 0.15.1

**Comment by royyeah** [comment]
I wanted to ask the same thing, can this logging be set to debug level?

**Comment by JamesBirdsall** [comment]
See PR#246
