### ISSUE TITLE
Feature request: share threads among EventHubClient instances

### ISSUE THREAD

**Issue by mmaitre314** [Azure/azure-event-hubs-java#207]
We need to connect to 1300+ Event Hubs to read data. The EventHubClient library has challenges scaling because CPU cores are over-commited with threads:

![image](https://user-images.githubusercontent.com/8584604/33001186-2855f862-cd61-11e7-8444-b406a02be6d4.png)

## Actual Behavior
1. Connect to a 1300 Event Hubs
2. 1300 threads are created resulting in CPU cores spending their time in context switches

## Expected Behavior
1. Connect to 1300 Event Hubs
2. A low number of threads (proportional to the number of CPU cores) are created, potentially using the WorkStealingPool.

## Versions  
- OS platform and version: Windows 10
- Maven package version or commit ID: 0.15.1

**Comment by sjkwak** [comment]
@mmaitre314, thanks for reporting the issue. This is one of changes that we will make as part of next major release.

**Comment by SreeramGarlapati** [comment]
#215 - is in line for next release - which addresses this issue.

**Comment by SreeramGarlapati** [comment]
with #215 #217  - javaclient shares threads across multiple instances. start development using our `dev` branch of `1.0.0-SNAPSHOT` - we hope to hear feedback !!
