### ISSUE TITLE
Eventhub availability check

### ISSUE THREAD

**Issue by Draczech** [Azure/azure-event-hubs-java#212]
## Problem
To simply present our use case: At the moment we use system of services in docker swarm and some of them are using event hubs for message transport. There is single service taking care of message processing, augmentation and dispatching the messages into Service bus queues.

Quite often there are some problems with docker network which result in the Event hubs being not reachable by the message dispatching service. It goes down quite silently actually. Automatic reconnection does not seem to work and trying to reconect manually just results in high resources allocation without actually connecting to the Event Hub.

I know there is a release planned for January 2018 which should improve thread and resource management for EPH we use. This might help to mitigate some symptomps we are experiencing.

## Question
Is there some way to detect actual availability of Event Hub from EPH? At the moment I plan to incorporate some checking by [Event Hub REST](https://msdn.microsoft.com/en-us/library/azure/dn790659.aspx). But if there are any standard tools for this, I'd gladly use them.

Thanks for any suggestions how to approach this issue.

## Versions  
- 0.14.5 + 0.14.4 for EPH
- I tried updating to 0.15.1 and we'll see if that helps. It is not possible to put newer version directly on production.

**Comment by sjkwak** [comment]
Hi @Draczech are you trying to delay starting EPH until network communication is recovered if network issue happens?

**Comment by Draczech** [comment]
The thing is the connection gets sometimes broken without anybody knowing about it and as far as I know EPH gets stuck in such case instead of just getting disconnected with an exception after some timeout or so. Maybe it tries to reconnect internally, but I haven't checked that myself on all log levels.
As such network state is definitely not desirable for us I haven't been able to do much debugging/testing in such conditions as we usually try to fix it as soon as it is detected.

If there is some specific log line I should watch to check EPH behaviour, let me know. I can enable the logs and see what comes up in upcoming days.

At the moment I created simple REST based checker which logs the Event Hub status every few seconds. But that is not anything I would call a solution...

**Comment by sjkwak** [comment]
Got it, it would help us debug the issue if you can capture and share logs with us. By the way, does the issue still occur in the latest version?

**Comment by Draczech** [comment]
I haven't seen the issue for a few days on our development environment. But that might be caused by the multiple updates we made there on the networking level and docker swarm version as well. When I am able to update all related libraries in our production environment to 0.15.1, I'll check the logs and let you know if there is any progress.

**Comment by JamesBirdsall** [comment]
Is there any update? Have you had a chance to try the 1.0 version and see if that helps?

**Comment by sjkwak** [comment]
Please reopen the issue if the issue still occurs.
