### ISSUE TITLE
Improper Output Neutralization for Logs (CWE ID 117) in MessageReceiver and MessageSender

### ISSUE THREAD

**Issue by yudhistira-arya** [Azure/azure-event-hubs-java#216]
## Actual Behavior
1.  Improper Output Neutralization for Logs (CWE ID 117) in `MessageReceiver` (line: 151) and `MessageSender` (line: 166). 

## Expected Behavior
1. **azure-eventhubs** should not contains any potential risk indicated by CWE (Common Weakness Enumeration) as this library is used by many enterprise projects with strict security policy.

## Versions  
- OS platform and version: **cross platform**. 
- Maven package version or commit ID: **0.15.1**

## How to Reproduce
1. Create any project that has compile dependency on **azure-eventhubs** version **0.15.1**. 
1. Build the project and upload the compiled jar + dependencies into Veracode static scan. 
1. Result will indicate _CWE ID 117_ in `com.microsoft.azure.eventhubs.MessageReceiver` line 151 and `com.microsoft.azure.eventhubs.MessageSender` line 166.

![image](https://user-images.githubusercontent.com/746670/35092510-98d076b0-fc7a-11e7-9e7e-866251fd66c7.png)

![image](https://user-images.githubusercontent.com/746670/35092474-77bc1ca4-fc7a-11e7-96cc-d9694a4163c4.png)

**Comment by SreeramGarlapati** [comment]
hi @yudhistira-arya - while trying to fix this - I have a question:

- what is the reason for these 2 lines to be special. I can see we have many places where we do exception.getMessage() added to our traces - why did the veracode scanner complain about only these 2 lines 

our exceptions are thrown by EventHubsService only - and no user can inject them form any where. Do you have any Idea on why these lines are flagged at all..

**Comment by yudhistira-arya** [comment]
Hi Sreeram, 

Thank you for looking into the issue. I'm in the midst of discussion with Veracode to see their reasoning behind this. I'll update you soon.

**Comment by SreeramGarlapati** [comment]
Hi @yudhistira-arya - did you hear back from Veracode. 
Thanks a lot for the help so far!

**Comment by SreeramGarlapati** [comment]
Hi @yudhistira-arya - did you get to hear back from Veracode.
Thanks again for pushing the quality of our library!

**Comment by yudhistira-arya** [comment]
Hi Sreeram, 

Sorry for the delayed reply. They still insist on the potential risk for CLRF injection, even after I explain to them that all of the logs is coming from the library itself (not from user). In the end, we managed to get exemption based on the following reasons:

1. The log doesn't get printed out in production. (Only ERROR and above is logged out)
1. Enabling newline escape at `logback.xml` level. 

Thank you for your assistance so far.
