### ISSUE TITLE
endpoint in ConnectionStringBuilder hard code to global azure

### ISSUE THREAD

**Issue by allenhula** [Azure/azure-event-hubs-java#22]
`final static String endpointFormat = "amqps://%s.servicebus.windows.net";`

should provide method to set endpoint to other Azures instead of hard code, such as mooncake (China Azure).

**Comment by SreeramGarlapati** [comment]
@allenhula - can you please try our latest versions (`0.9.0`) - this has the constructors which accepts the endpoints as you suggested:

`public ConnectionStringBuilder(
			final URI endpointAddress, 
			final String entityPath, 
			final String sharedAccessKeyName,
			final String sharedAccessKey)`

**Comment by allenhula** [comment]
Yes. It worked! Thanks!

**Comment by SreeramGarlapati** [comment]
Thanks for the verification @allenhula - and btw - we just released https://github.com/Azure/azure-event-hubs-java/releases/tag/0.10.0...
