### ISSUE TITLE
Detail lacking on expected values for environment variables to enable testing

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-event-hubs-java#221]
The readme.md file states that to run the unit tests in the azure-event-hubs-java project, we must set the following three environment variables:

1. EVENT_HUB_CONNECTION_STRING

1. PARTITION_COUNT

1. EPHTESTSTORAGE

What the docs do not make clear to a layperson such as myself is what the expected values are here. I am trying to build locally simply to get everything compiling under JDK 8 and JDK 9, as well as to work on any JavaDoc issues, and I'm blocked until I can get some further information. If you could clarify here or in the readme.md file, that would be much appreciated! Thanks.

**Comment by SreeramGarlapati** [comment]
Hi @JonathanGiles - please use `mvn package -Dmaven.test.skip=true javadoc:javadoc` to build locally.

**Comment by JonathanGiles** [comment]
Regarding the last paragraph - can you please clarify the steps required? I would ideally love to see a situation where this is handled automatically - currently my scripts literally git clone the repos, followed by `mvn clean package` and `mvn javadoc:javadoc`

**Comment by SreeramGarlapati** [comment]
This is how we run - as part of our appveyor pull request build validation:
`mvn clean package -Dmaven.test.skip=true javadoc:javadoc`
- am not sure if there is any difference between running them 'saperately' vs 'as part of same command' - which I guess is probably the reason - why the `mvn Javadoc:javadoc` command is failing..

**Comment by JonathanGiles** [comment]
Could you please review the JavaDoc output [here](https://jonathangiles.github.io/azure-javadocs/index.html?overview-summary.html) and tell me whether it contains all expected JavaDocs for the azure-event-hubs-java project?

**Comment by SreeramGarlapati** [comment]
Thanks a lot for doing javadoc for our library @JonathanGiles... I love this - & always missed it. 

Is there any way to selectively pick & show only specific classes? For Example in `com.microsoft.azure.eventhubs` package - we need to show only below classes:
`EventHubClient`, 
`PartitionSender`, 
`PartitionReceiver`, 
`EventData`, 
`EventDataBatch`
`ReceiverOptions`,
`ReceiverRuntimeInformation`,
`PartitionReceiveHandler`,
`*Exception.java` classes

&
`com.microsoft.azure.eventhubs.extensions.appender` - not needed - as this package is not released yet.
`com.microsoft.azure.eventhubs.amqp` - we don't need any classes from this package.

@JamesBirdsall - will provide list of classes needed in `com.microsoft.azure.eventprocessorhost`.

**Comment by SreeramGarlapati** [comment]
Also, is it possible to show the library version in the javadocs?
for ex: what we have in our `master` branch is what was released as `version 0.15.1`.
For our upcoming `1.0.0` version we have a bit different API's. Is it possible to capture them independently?

**Comment by JonathanGiles** [comment]
Packages that are not public API should either be made package-protected or private, or moved to an impl package that you deem to not be part of the public API. With the advent of JDK 9, we should eventually see these impl packages removed from the public API scope entirely.

Regarding packages that should not be included - by default I don't want to remove any package - if it is in the github repo I would like to initially have it as part of the documentation. In the fullness of time I might make a separate document that only includes the approved public API for a given release and version details, but right now my focus is solely on ensuring everything builds.

**Comment by JonathanGiles** [comment]
Thanks!
