### ISSUE TITLE
JavaDoc @throws statements do not match with API

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-event-hubs-java#228]
Try running `mvn javadoc:aggregate` on a fresh clone of the repo. You'll see a lot of errors (ignoring the warnings) due to classes like ILeaseManager declaring in the javadoc that it throws an exception when the method declaration itself does not declare that. This means there is a mismatch between the stated behavior and the specified behavior, and this results in javadoc errors preventing a clean build of all javadocs for this project. 

Please consider whether you should remove the `@throws` javadoc annotations from all places you see warnings for in the build when running `mvn javadoc:aggregate`, or else updating the API spec to match the documented behavior.

**Comment by JamesBirdsall** [comment]
The upcoming 1.0 release has tweaked a lot of the APIs in Event Processor Host. As part of that, I have gone through and scrubbed all Javadocs for the Event Processor Host, adding ones that were missing and updating the existing ones. There will be a PR with the docs update soon.

**Comment by sjkwak** [comment]
We believe the issue was fixed. Please reopen the issue if the issue still occurs.
