### ISSUE TITLE
FeatureRequest: PublisherId

### ISSUE THREAD

**Issue by pgbhagat** [Azure/azure-event-hubs-java#233]
Using EventHubClient 0.15.1

Generated SAS token using SharedAccessSignatureTokenProvider.getToken(resource, tokenTimeToLive)
When input arg 'resource' is in format like
(amqp OR amqps OR sb)://" + namespaceName + ".servicebus.windows.net/" + entityPath + "/publishers/"+ applianceId

i tried with all uri in combination with prefix 'amqp OR amqps OR sb'

CBSChannel throws below error during token validation

com.microsoft.azure.eventhubs.AuthorizationFailedException: Put token failed. status-code: 401, status-description: InvalidAudience: The authorization header contains a token with a wrong audience., errorContext[NS: mynamespace.servicebus.windows.net, PATH: myeventhub]
	at com.microsoft.azure.eventhubs.ExceptionUtil.amqpResponseCodeToException(ExceptionUtil.java:76)
	at com.microsoft.azure.eventhubs.CBSChannel$1$1.onComplete(CBSChannel.java:75)
	at com.microsoft.azure.eventhubs.CBSChannel$1$1.onComplete(CBSChannel.java:65)
	at com.microsoft.azure.eventhubs.amqp.RequestResponseChannel$ResponseHandler.onReceiveComplete(RequestResponseChannel.java:229)
	at com.microsoft.azure.eventhubs.amqp.ReceiveLinkHandler.onDelivery(ReceiveLinkHandler.java:85)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:185)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
	at com.microsoft.azure.eventhubs.MessagingFactory$RunReactor.run(MessagingFactory.java:404)
	at java.lang.Thread.run(Thread.java:748)

## Actual Behavior
1. In my case, i need SAS token for an resource with format
(amqps://" + namespaceName + ".servicebus.windows.net/" + entityPath + "/publishers/"+ applianceId
2. SAS token generated using above resource uri, CBSChannel errors out with code 401.

## Expected Behavior
1. I should be able to validate SAS token with publishers included in resource uri
2. 

## Versions  
- OS platform and version:
- Maven package version or commit ID:

**Comment by SreeramGarlapati** [comment]
Hi @pgbhagat,

Are you trying to use PublisherId feature in EventHubs? Did your scenario need it?
sending to a specific publisher is not supported in javaclient yet. please remove /publishers/publisherid from path and it should work.

**Comment by pgbhagat** [comment]
Hi Sreeram,

Yes. We need to use publisher id while using event hub. Generation of sas
token using publisher id.

Thanks
Prashant

On Feb 10, 2018 3:53 AM, "Sreeram Garlapati" <notifications@github.com>
wrote:

Hi @pgbhagat <https://github.com/pgbhagat>,

Are you trying to use PublisherId feature in EventHubs? Did your scenario
need it?
sending to a specific publisher is not supported in javaclient yet. please
remove /publishers/publisherid from path and it should work.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Azure/azure-event-hubs-java/issues/233#issuecomment-364586634>,
or mute the thread

**Comment by pgbhagat** [comment]
Hi Sreeram,
What it takes to support publishes id while sending data using java
EventHub library?
I will contribute. Does equivalent .NET library supports this use case?
We need this feature, I appreciate your help.

Thanks,
Prashant

**Comment by SreeramGarlapati** [comment]
It is an API addition to EventHubClient - `CreatePublisher`.
We will need to align our coreclr and java clients for API additions. I will discuss with my team (@sjkwak , @serkantkaraca ) and get back to you by EOD.

**Comment by SreeramGarlapati** [comment]
We found a design issue with our current Publisher Policy implementation in the EventHubs service. Publisher Policy is supposed to be a security feature but, also controls the partition distribution strategy of the published message. As a result, users who use Publisher Id feature cannot set PartitionKey or Cannot send to a specific eventhubs partition. We want to fix this and re-design this feature on our Service. 

We will make necessary changes in the java client once we have this in place in our Service. Apologies for the inconvenience.

**Comment by SreeramGarlapati** [comment]
Hi @pgbhagat
Can you please explain the scenario you are trying to solve with PublisherId?

**Comment by SreeramGarlapati** [comment]
Hi @pgbhagat 

Here's a sample on How to send to Publisher using the existing java client code:

```
final String publisherName = "publisherid123"; // *********replace this with your publisher value

final ConnectionStringBuilder connectionStringFromAzurePortalWithSasPolicy = new ConnectionStringBuilder("Endpoint=sb://NAMESPACE_NAME.servicebus.windows.net/;SharedAccessKeyName=somekey;SharedAccessKey=SAS_KEY_VALUE;EntityPath=EVENTHUB_NAME");
final String entityPathWithPublisher = connectionStringFromAzurePortalWithSasPolicy.getEntityPath() + "/Publishers/" + publisherName;
final String namespaceUrl = connectionStringFromAzurePortalWithSasPolicy.getEndpoint().toString();

final String publisherConnectionString = String.format("Endpoint=%s;EntityPath=%s;SharedAccessSignature=%s",
        namespaceUrl,
        entityPathWithPublisher,
        SharedAccessSignatureTokenProvider.generateSharedAccessSignature(
                connectionStringFromAzurePortalWithSasPolicy.getSasKeyName(),
                connectionStringFromAzurePortalWithSasPolicy.getSasKey(),
                namespaceUrl + entityPathWithPublisher,
                Duration.ofMinutes(1)));

// Note: This EventHubClient instance cannot be used for any other operations like createReceiver - other than sending
final EventHubClient ehClientWhichCanBeUsedToSendToPublisherButNothingElse = EventHubClient.createFromConnectionStringSync(publisherConnectionString.toString());

ehClientWhichCanBeUsedToSendToPublisherButNothingElse.sendSync(new EventData("test message".getBytes()));
```

Please Note that, today, in our EventHubs Service - we have an undesirable side-effect of using Publisher Policy feature (as I described earlier). PublisherId will be used as PartitionKey.

I will wait to hear back from you - how it went!

**Comment by pgbhagat** [comment]
Tried this way, but now seeing new error

com.microsoft.azure.eventhubs.AuthorizationFailedException: Unauthorized access. 'Send' claim(s) are required to perform this operation. Resource: 'sb://<mynamespace>.servicebus.windows.net/<myeventhub>/publishers/<publisher GUID>'. TrackingId:57f2c5215bfc452e8350ca4a76bd1a26_G25, SystemTracker:gateway6, Timestamp:2/15/2018 5:49:04 AM, errorContext[NS: mynamespace.servicebus.windows.net, PATH: myeventhub/Publishers/publisher GUID, REFERENCE_ID: 860d26_a26_G25_1518673744712]
	at com.microsoft.azure.eventhubs.ExceptionUtil.toException(ExceptionUtil.java:37)
	at com.microsoft.azure.eventhubs.MessageSender.onClose(MessageSender.java:375)
	at com.microsoft.azure.eventhubs.amqp.BaseLinkHandler.processOnClose(BaseLinkHandler.java:76)
	at com.microsoft.azure.eventhubs.amqp.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:47)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
	at com.microsoft.azure.eventhubs.MessagingFactory$RunReactor.run(MessagingFactory.java:404)
	at java.lang.Thread.run(Unknown Source)

I am generated the SAS token using SAS key name as 'RootManageSharedAccessKey' which has all permissions as Manage/Send/Listen claims.

**Comment by pgbhagat** [comment]
Anyway, we do not want to use anything which has undesirable side-effect of using Publisher Policy feature.

**Comment by SreeramGarlapati** [comment]
No problem - thanks for trying; I tried the code before posting - I am sure i can get the code running if I get a chance to see the real values supplied.

As you no longer want to use this feature - I am considering  the issue closed.

**Comment by pgbhagat** [comment]
I think we should have this feature in place i.e. sending messages using event hub specific to publisher. When i am saying we do not want to use anything which has undesirable side-effects means not as per the sample you have provided. Please align coreclr and java clients for publisher based API additions.

**Comment by SreeramGarlapati** [comment]
Sure, I will keep this thread posted when we implement this feature in EventHubs Service.

If you want to use the Publisher policy feature - in the current state - as it is present in our Service - please use the above code sample. The code sample itself doesn't have any side-effect - **the service implementation has the side-effect**.

**Comment by pgbhagat** [comment]
Thanks Sreeram
