### ISSUE TITLE
EventDataBatch.tryAdd throws BufferOverflowException

### ISSUE THREAD

**Issue by kevinhartman** [Azure/azure-event-hubs-java#235]
## Actual Behavior
1. `EventDataBatch.tryAdd` throws `java.nio.BufferOverflowException` when adding an event greater than 256KB in size.

## Expected Behavior
1. Should return `false` rather than crashing.

## Details
This is happening because the buffer allocated to encoding the message in `EventDataBatch.getSize` is limited to 256KB, which is insufficient for messages that cannot fit in the batch even by themselves.

## Versions  
- OS platform and version: N/A
- Maven package version or commit ID: 3deac08bcc9094734644fd10f0a8dd45b711b428

**Comment by kevinhartman** [comment]
@sabeegrewal :)

**Comment by sabeegrewal** [comment]
Yo! What version are you running? We're gearing up for a release soon (~mid-Feb), so I'll make sure we get this fix in. 

P.S. I fixed the partition key issue with EventDataBatch as well, so you can send without a partition key being set.

**Comment by kevinhartman** [comment]
Fantastic!

I'm running with `0.15.1` which I believe is latest non-preview.

If anyone has extra cycles, it'd be really nice to add a helper that automatically creates `DataEventBatch`s (plural) given a `Seq[EventData]`. Right now I have some code that looks like this which is pretty ugly to have in client code:

```scala
val client = EventHubClient(connStr)

var batch = client.createBatch()
while (partition.hasNext) {
  val event = partition.next

  if (!batch.tryAddWorkaround(event)) {
    if (batch.getSize > 0) {
      // Send filled batch to EventHub
      client.sendSync(batch.iterator)

      // Initialize a new empty batch
      batch = client.createBatch()
    }

    // Retry adding event into empty batch
    if (!batch.tryAddWorkaround(event)) {
      // Single event > 256KB. For now, send alone to trigger correct message too big error.
      client.sendSync(event)
    }
  }
}

if (batch.getSize > 0) {
  // Send last batch to EventHub
  client.sendSync(batch.iterator)
}
```

**Comment by sabeegrewal** [comment]
Hey Kevin, for the next release, we're not gonna include that method. We have to release soon and we don't have the cycles to add the functionality and test it in stress at the moment. 

Also, instead of returning false, we're going to throw a `PayloadSizeExceededException`. If you pass a single `EventData` to `send`, it will throw that exception for data that's too large. So, in your code, you can catch that exception and handle it as you see fit.
