### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by vyshaliN** [Azure/azure-event-hubs-java#265]
I'm receiving events using the EventProcessorHost.I followed the steps specified in [link](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-java-get-started-receive-eph).There is no error with the connecting string and the storage account details.But I'm getting the error "Failure while registering: java.lang.NoSuchMethodError: com.microsoft.azure.eventhubs.EventHubClient.getRuntimeInformation()Ljava/util/concurrent/CompletableFuture".Please help with the resolution.

**Comment by JamesBirdsall** [comment]
Are you running with different versions of the EPH JAR and the event hub client JAR? That seems like the most likely thing to cause this error, a newer EPH JAR and a much older client JAR that doesn't have getRuntimeInformation. The recommendation is to always run the same version of both.

**Comment by JamesBirdsall** [comment]
Any update on this issue?

**Comment by SreeramGarlapati** [comment]
@vyshaliN - thanks a lot for reporting the issue.
Please fix dependencies on your pom.xml - to make sure EPH and EventHubs client versions are compatible - to eliminate this error.
