### ISSUE TITLE
 azure-eventhubs version 0.8.2 is no longer working

### ISSUE THREAD

**Issue by anushkaee** [Azure/azure-event-hubs-java#289]
we have implemented IoT Hub  consumers  using Java SDK  azure-eventhubs version 0.8.2 . It  was working properly untill 2 weeks back but now suddenly stopped consuming events. It seems you have done something to IoT hub or Java SDK without maintaining the backward compatibility. Our systems are not working properly due to this issue.  is version 0.8.2 deprecated ?

## Actual Behavior
1. Not Consuming events

## Versions  
- Azure EventHubs » 0.8.2

**Comment by JamesBirdsall** [comment]
What errors do you get? Are receives timing out when events are available, or are you getting exceptions?

**Comment by anushkaee** [comment]
nothing happens. no any error logs or exceptions but it doesn't consume  data from the hub. it acts like there is no data in the hub but when we  monitor the devices using device explorer we could see that data were receiving from iot devices.

**Comment by SreeramGarlapati** [comment]
What library do you use to consume events? `EventProcessorHost`? or do you directly consume using `PartitionReceiver.receive()` API.

We did not do anything explicitly to deprecate/block version `0.8.2`. Infact my tests for 0.8.2 to cover receive scenarios from EventHubClient library just worked fine.

may I please request you to - debug through and find out exact errormessages - so that we have something actionable to help :).

**Comment by anushkaee** [comment]
We used EventProcessorHost to consume events. we don't see any errors or exceptions but noticed partitions are not opening. our consumer app worked fine more than a year. we believe some recent change in azure side may cause this error.

**Comment by SreeramGarlapati** [comment]
Hi @anushkaee - I would really appreciate if you can either:
- provide logger traces for EPH & java client for you scenario
- or if you can give us code/project - which can reproduce this issue.
- or enable proton amqp traces and attach the logs - set environment variable `PN_TRACE_FRM=1` - to collect the traces.

From EventHubs service perspective - be assured that nothing changed.

I am here to help understand whats going on and can do it well - if you can provide specific actionalble information like: Exception stacktraces or traces etc. :)

Thanks a lot for reporting the issue and sorry about the delay.
