### ISSUE TITLE
Unable to recover from reactor errors

### ISSUE THREAD

**Issue by aciduck** [Azure/azure-event-hubs-java#298]
## Actual Behavior
If the reactor crashes, because of an handler error or for any other reason, an open partition receiver remains hanging without getting any error or more events.

## Expected Behavior
The MessagingFactoryonReactorError() method should restart the reactor in case of error. From what I can tell, it does create a new reactor but with an empty handler, not opening another AMQP connection. 
See the difference between the call to startReactor() there and in createConnection().

## Versions  
- OS platform and version: Windows 10
- Maven package version: 0.14.5, 1.0.1

## Code sample
```java
EventHubClient eventHubClient = EventHubClient.create(
	"...",
	Executors.newCachedThreadPool()
).get(1, TimeUnit.MINUTES);
PartitionReceiver partitionReceiver = eventHubClient.createEpochReceiver("...", "0", EventPosition.fromStartOfStream(), System.currentTimeMillis()).get(1, TimeUnit.MINUTES);
partitionReceiver.setReceiveHandler(new MyPartitionReceiveHandler()).get(1, TimeUnit.MINUTES);

MessagingFactory underlyingFactory = (MessagingFactory) FieldUtils.readField(eventHubClient, "underlyingFactory", true);
Reactor reactor = (Reactor) FieldUtils.readField(underlyingFactory, "reactor", true);
Handler handler = reactor.getHandler();
handler.add(new BaseHandler() {
	@Override
	public void handle(Event e) {
		//System.out.println("fail");
		//throw new RuntimeException();
		super.handle(e);
	}
});

TimeUnit.MINUTES.sleep(30);
System.out.println("done");

private static class MyPartitionReceiveHandler implements PartitionReceiveHandler {

	@Override
	public int getMaxEventCount() {
		return 100;
	}

	@Override
	public void onReceive(Iterable<EventData> events) {
		System.out.println("data");
	}

	@Override
	public void onError(Throwable error) {
		System.out.println("error" + error);
	}
}
```

When running this code we get multiple lines with "data" in them. If you uncomment the first two lines in handle() and comment the last one, you only get one "fail" line, and no other error indicator or ability to recover.

**Comment by SreeramGarlapati** [comment]
Timer thread is also running on reactor thread. Once, there is a failure on Reactor - timer for the next operation is not run. I will work on the fix soon.
