### ISSUE TITLE
Cannot receive device id when connecting to Event Hub-compatible endpoint on IoT Hub

### ISSUE THREAD

**Issue by dominicbetts** [Azure/azure-event-hubs-java#30]
I'm using the SDK to connect to an Event Hub-compatible endpoint on an IoT hub.

If I use version 0.7.8 of this SDK, the following code returns the device id correctly:

```
receivedEvent.getProperties().get("iothub-connection-device-id")));
```

In version 0.8.0 onwards, this code returns `null`.

**Comment by SreeramGarlapati** [comment]
@dominicbetts 

can you please check if they are present in `receivedEvent.getSystemProperties()`
Apologies if we broke you (https://github.com/Azure/azure-event-hubs-java/releases/tag/0.8.0).

**Comment by dominicbetts** [comment]
@SreeramGarlapati - it works with **getSystemProperties** - Thanks!

**Comment by SreeramGarlapati** [comment]
Thanks for super quick response @dominicbetts
