### ISSUE TITLE
Too much logging!

### ISSUE THREAD

**Issue by markthegrea** [Azure/azure-event-hubs-java#302]
## Actual Behavior
1. We get an absurd amount of INFO logging when reading from ehubs

## Expected Behavior
1. Can we change some of this to "TRACE"?
2. 

## Versions  
- Windows
- Maven package version or commit ID: version 1.0.0

**Comment by JamesBirdsall** [comment]
Can you give some examples of messages which are spamming you? We already did one pass with PR#246, which moved most info logging down to debug for the 1.0.0 release. The remaining info messages aren't expected to happen very often. If we missed moving a noisy one, we'd like to fix that.

**Comment by markthegrea** [comment]
[logging.txt](https://github.com/Azure/azure-event-hubs-java/files/1877141/logging.txt)

This file contains just one section of INFO logs that are spitting out.  This is one "grab" from an ehub.  It seems a bit much.

**Comment by JamesBirdsall** [comment]
OK, that explains it -- PR#246 was only for logging in Event Processor Host, and the messages you're seeing are coming from the underlying client. I don't know if there was a reason Sreeram left those as INFO. I have assigned this issue to him.

**Comment by SreeramGarlapati** [comment]
@markthegrea

Thanks a lot for filing the issue!

The log file you attached has the activity relating to EntityClose and Open - which is very useful for debugging any failures while Sending from EventHub. The logging pattern keeps high throughput sender in mind and tries to capture - `only Connection and Link level` activity`. We believe all of this is very important and donot see anything particular that can be removed. 
Please review our tracing strategy here: https://github.com/Azure/azure-event-hubs-java/pull/158 

Please reopen the issue & let us know if you feel the need to discuss any specific trace to be removed.
