### ISSUE TITLE
Re-establish inactive connections in getPartitionRuntimeInformation path

### ISSUE THREAD

**Issue by sabeegrewal** [Azure/azure-event-hubs-java#304]
Currently, if we make a `getRuntimeInformation` call on an inactive connection, the retries will fail and an exception is thrown to the user. 

Instead, we should re-establish the underlying connection.

**Comment by SreeramGarlapati** [comment]
After investigating the error a bit, I found that - retries are working as expected. Connection error bubbles up to the user - as the operation took beyond the configured timeout.

However, there is an issue with `Timeout` enforcement on the Client - which will be addressed as part of #312.
