### ISSUE TITLE
Question: can we expose an API that return the actual size of eventData

### ISSUE THREAD

**Issue by lhaiesp** [Azure/azure-event-hubs-java#305]
Hi,

We want to get the actual size of the AMQP message (which should include eventBody, system properties, properties and keys, etc.). Just like the getSize() method in EventDataBatch class. Is this doable?

We want to get this info for some bookkeeping (e.g. metrics) and also to skip messages that are oversized.

Thanks,
Hai

**Comment by markthegrea** [comment]
I would like to pipe in here.  There is also a requirement for the payload to not be over 250kb.  This made us squirm for a bit as well.  We got the bytes of the string payload but still had problems with the payload being too big. We finally figured out to add the Hashmap of properties to the size.  Works like a charm.  however, to get the size of the hashmap, we do a "toString" on the hashmap.

All this is very cluncky, but I am not sure what else can be done.  It would be great to have a method to do this.  A requirement for size needs to be accompanied by a way to figure it out.

**Comment by SreeramGarlapati** [comment]
This is a new API addition - so requires minor version update. sorry about the change.

**Comment by kai18** [comment]
I'd like to take up this issue.

**Comment by JamesBirdsall** [comment]
This client is now legacy and in maintenance mode. We will not be adding new features. You can find the new Java Event Hubs client at https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/azure-messaging-eventhubs -- if you feel this issue should still be addressed, please open it there.
