### ISSUE TITLE
instrument javaclient with performance metrics

### ISSUE THREAD

**Issue by SreeramGarlapati** [Azure/azure-event-hubs-java#307]
These are the metrics most of the customers try and measure - including them directly in the client sdk can benefit many:
1. latency of connection creation, sender & receiver creation 
2. percentile latencies of `send` operations (.999 .99 avg)
3. percentile latencies of `receive` operations
I believe, there are more items to be added here. This will serve as first cut.

**Comment by conniey** [comment]
There is a customer issue about trying to get some metrics for track 2. https://github.com/Azure/azure-sdk-for-java/issues/19391

**Comment by JamesBirdsall** [comment]
This client is now legacy and in maintenance mode. We will not be adding new features. You can find the new Java Event Hubs client at https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/azure-messaging-eventhubs -- this issue is already open there at the link above.
