### ISSUE TITLE
MessagingFactory throws error on shutdown.

### ISSUE THREAD

**Issue by markthegrea** [Azure/azure-event-hubs-java#311]
When executing Host.unregisterEventProcessor() we get an error after about 30-50 seconds.  Not sure if this is a bad thing or not but should be fixed.  Looks like something is not getting de-registered.

 2018-05-02 15:19:55 WARN  c.m.a.e.i.MessagingFactory:451 - messagingFactory[MessagingFactorye3831d], hostName[dev-cmdout-cmdr-usnc-cat-eh-01.servicebus.windows.net], error[scheduling reactor failed
Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2673e94d rejected from java.util.concurrent.ScheduledThreadPoolExecutor@72389672[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 22106]
java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622)
com.microsoft.azure.eventhubs.impl.MessagingFactory$RunReactor.run(MessagingFactory.java:447)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)]

## Versions  
-- version 1.0.0

**Comment by SreeramGarlapati** [comment]
@markthegrea - me & @JamesBirdsall - debugged thru this and found out that - `EPH` leaked 1 instance of `EventHubClient` (which is used to query `PartitionInformation` during `EPH` startup) - which is actively using the `ExecutorService` and hence the error - expect a fix soon.
