### ISSUE TITLE
Documentation: Broken Link, Outdated Code Snippet and Dependency Version

### ISSUE THREAD

**Issue by brunoborges** [Azure/azure-event-hubs-java#318]
Documentation [page](https://docs.microsoft.com/en-us/java/api/overview/azure/eventhub) has outdated version, examples, and broken links.

**Comment by SreeramGarlapati** [comment]
Thanks @brunoborges for watching out! 
This PR should takecare: https://github.com/Azure/azure-docs-sdk-java/pull/470

**Comment by brunoborges** [comment]
Thanks
