### ISSUE TITLE
EPH 1.0.1 was not deployed to Maven Repository

### ISSUE THREAD

**Issue by grnadav** [Azure/azure-event-hubs-java#319]
## Actual Behavior
1. Latest version on mvnrepository is 1.0.0, in mismatch to azure-eventhubs-1.0.1, missing crucial fixes
2. 

## Expected Behavior
1. mvn repository to have version 1.0.1 of azure-eventhubs-eph
2. 

## Versions  
- OS platform and version:
- Maven package version or commit ID:

**Comment by JamesBirdsall** [comment]
There is no 1.0.1 release of Event Processor Host. The client had an important fix (see https://github.com/Azure/azure-event-hubs-java/releases/tag/1.0.1 ) and needed to release, but at the time EPH had no changes pending, so it remained at 1.0.0.
