### ISSUE TITLE
EventHubClient.send call hangs when a closed connection is used.

### ISSUE THREAD

**Issue by markthegrea** [Azure/azure-event-hubs-java#323]
## Actual Behavior
1. When a closed connection is used, the client "hangs" and never comes back.

## Expected Behavior
1. When a closed connection is used, the client should throw some kind of "connection closed" exception.

Test:
```
EventHubClient ehc = this.factory.fetchClient(message.getDestination());
ehc.close();
ehc.sendSync(sendEvent);
```

We have an app that refreshes the connection every 5 minutes.  It is an application that does not use the connections for hours and hours.  Anyway, during the swap (new connection for old connection) we close a connection and then get another one.  Our bug is a timing one and we are fixing that.  We have a listener that is listening to an EHub  and then sends some data to another EHub.  This bug has, however, ruined the IEventProcessor because, since the onEvent() never completes (its hanging), the partition is "dying".

Trying to use a closed connection should always throw an Exception.  Not sure why this never comes back, but this is dangerous.

## Versions  
- OS platform and version:  All?
- Maven package version or commit ID:  1.0.0

**Comment by SreeramGarlapati** [comment]
This is supposed to throw this error:
`java.lang.IllegalStateException: Operation not allowed after the com.microsoft.azure.eventhubs.impl.MessageSender instance is Closed.`

for ex: if you run this snippet - you will see that:

```java
final EventHubClient ehc = createClient();
ehc.sendSync(sendEvent);
ehc.close();
ehc.sendSync(sendEvent);
```

the first send creates the required infrastructure and hence, that error is missing. I will fix that soon.
