### ISSUE TITLE
no epoch

### ISSUE THREAD

**Issue by nysthee** [Azure/azure-event-hubs-java#324]
Is it possible to use EventProcessorHost with multiple receivers per partition?

**Comment by JamesBirdsall** [comment]
Event hubs inherently do not support competing consumers on a partition. Unlike a queue or topic, every receiver on an event hub partition will see all the events, so having more than one does not result in events being processed more quickly. With event hubs, you increase parallelism and throughput by increasing the number of partitions. Therefore, one EventProcessorHost instance (or group of host instances sharing the same event hub+consumer group) will only open one receiver per partition.

If you are asking about something else, perhaps you could elaborate on what you're trying to achieve?

**Comment by nysthee** [comment]
Hi James

Thanks for the swift feedback. I thinks this answers my question!
