### ISSUE TITLE
Make sure "No connection handler was found for virtual host" is retried. 

### ISSUE THREAD

**Issue by sabeegrewal** [Azure/azure-event-hubs-java#327]
Hey I've gotten two reports of Spark jobs going down due to this issue in the last couple days. Let me know if you'd like any info, and I'll do my best to collect it!

**Comment by SreeramGarlapati** [comment]
@sabeegrewal - can you please check if #354 fixes the issue.

**Comment by sabeegrewal** [comment]
just updated the PR to close this out - looks like it'll handle the issue!
