### ISSUE TITLE
Azure event hub management sdk get unexisting namespace return NPE

### ISSUE THREAD

**Issue by warrenzhu25** [Azure/azure-event-hubs-java#332]
## Actual Behavior
Below code return NEP if namespace is not existed
```java
azure.eventHubNamespaces().getByResourceGroup(resourceGroup, namespace);
```

## Expected Behavior
1. Return null  
2. It would be better to have a method to return bool to determine whether a namespace exists or not

## Versions  
- azure 1.8.0

**Comment by SreeramGarlapati** [comment]
lets please file & track this on management sdk repository. started an email thread with @warrenzhu25
