### ISSUE TITLE
Provide to a way to checkpoint by partitionId, sequence number or offset

### ISSUE THREAD

**Issue by warrenzhu25** [Azure/azure-event-hubs-java#333]
## Actual Behavior
1.  `PartitionContext` only has 2 public method `checkpoint()` and `checkpoint(EventData)`

## Expected Behavior
1.  Provide method `checkpoint(partitionId, offset, sequenceNumber)`

## Versions  
- azure-eventhubs-eph 1.0.0

**Comment by JamesBirdsall** [comment]
Can you describe your use case where the existing methods are not sufficient? Thanks!

**Comment by warrenzhu25** [comment]
The typical use case is that I convert `EventData` into our specific message type, then pass this to other processor. Only the final processor success processed this, then checkpoint will be done. In currently implementation, I have to pass `EventData`.

**Comment by JamesBirdsall** [comment]
An important constraint is that offset and sequence number must be a matching pair (from the same event) and the proposed API offers no way to enforce that. It may be possible to create an equivalent API using EventPosition, which is much lighter-weight than keeping the entire EventData around. Doing so will require minor changes to the underlying client as well as EPH but that's not prohibitive. Will consider for the next EPH release.

**Comment by conniey** [comment]
In Track 2, you can implement your own CheckpointStore interface. So you can checkpoint however you wish.
https://azuresdkdocs.blob.core.windows.net/$web/java/azure-messaging-eventhubs/5.7.0/com/azure/messaging/eventhubs/CheckpointStore.html

**Comment by JamesBirdsall** [comment]
EventProcessorHost is now a legacy client in maintenance mode and we will not be adding features.
