### ISSUE TITLE
Support to register EventProcessorHost to certain partition

### ISSUE THREAD

**Issue by warrenzhu25** [Azure/azure-event-hubs-java#334]
## Actual Behavior
1. EventProcessorHost will listen all partions

## Expected Behavior
1. Support to register EventProcessorHost to only specified partition like Kafka

## Versions  
- azure-eventhubs-eph 1.0.0

**Comment by JamesBirdsall** [comment]
The fundamental purpose of Event Processor Host is to provide scalability and resilience, including automatically rebalancing partitions as processor instances start up or shut down/fail. We have no plans to change that design. For applications which desire the Kafka behavior, we now support Kafka clients running against event hubs: https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-for-kafka-ecosystem-overview

(Warren, I know you already know about our Kafka support. The link is for the benefit of anyone else who may look at this issue.)
