### ISSUE TITLE
Not reacquiring lease after LeaseLostException 

### ISSUE THREAD

**Issue by royyeah** [Azure/azure-event-hubs-java#336]
## Actual Behavior
We use an EventProcessorHost to forward events to an external system. Some values are missing here and I got the assumption that it was caused by 2 (out of 32) processors losing their lease and throwing a LeaseLostException and not being able to reacquire it.

I am trying to trace what has happened after the following consecutive log lines:

> 2018-06-03 14:35:56,378 WARN  [Thread-10] n.e.a.e.c.r.EventProcessor - Checkpointing failed for partition 1: com.microsoft.azure.eventprocessorhost.ExceptionWithAction: com.microsoft.azure.storage.StorageException: The client could not finish the operation within specified maximum execution timeout.
> 2018-06-03 14:36:12,220 WARN  [Thread-33] n.e.a.e.c.r.EventProcessor - Checkpointing failed for partition 21: com.microsoft.azure.eventprocessorhost.ExceptionWithAction: com.microsoft.azure.eventprocessorhost.LeaseLostException: Lease lost
> 2018-06-03 14:36:12,220 WARN  [Thread-27] n.e.a.e.c.r.EventProcessor - Checkpointing failed for partition 7: com.microsoft.azure.eventprocessorhost.ExceptionWithAction: com.microsoft.azure.eventprocessorhost.LeaseLostException: Lease lost

I wonder whether after this the lease is ever reacquired. Searching for 'lease' shows no log statement (within the time frame of a day) that the lease was reacquired.

I do see these type of warnings:

> 2018-06-04 05:34:55,589 WARN  [pool-2-thread-2] c.m.a.e.AzureStorageCheckpointLeaseManager - host example-ef9ae186-7df0-483a-8f5e-4dc334d31459: 14: Failure while getting lease details
> com.microsoft.azure.storage.StorageException: The client could not finish the operation within specified maximum execution timeout.
> 	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:233)
> 	at com.microsoft.azure.storage.blob.CloudBlob.exists(CloudBlob.java:1892)
> 	at com.microsoft.azure.storage.blob.CloudBlob.exists(CloudBlob.java:1879)
> 	at com.microsoft.azure.eventprocessorhost.AzureStorageCheckpointLeaseManager.getLeaseInternal(AzureStorageCheckpointLeaseManager.java:416)
> 	at com.microsoft.azure.eventprocessorhost.AzureStorageCheckpointLeaseManager.lambda$getLease$10(AzureStorageCheckpointLeaseManager.java:399)
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.util.concurrent.TimeoutException: The client could not finish the operation within specified maximum execution timeout.
> 	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:232)
> 	... 12 more
> 2018-06-04 05:34:55,610 WARN  [pool-2-thread-6] c.m.a.e.PartitionManager - host example-ef9ae186-7df0-483a-8f5e-4dc334d31459: Exception stealing lease
> com.microsoft.azure.storage.StorageException: The client could not finish the operation within specified maximum execution timeout.
> 	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:233)
> 	at com.microsoft.azure.storage.blob.CloudBlob.exists(CloudBlob.java:1892)
> 	at com.microsoft.azure.storage.blob.CloudBlob.exists(CloudBlob.java:1879)
> 	at com.microsoft.azure.eventprocessorhost.AzureStorageCheckpointLeaseManager.getLeaseInternal(AzureStorageCheckpointLeaseManager.java:416)
> 	at com.microsoft.azure.eventprocessorhost.AzureStorageCheckpointLeaseManager.lambda$getLease$10(AzureStorageCheckpointLeaseManager.java:399)
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.util.concurrent.TimeoutException: The client could not finish the operation within specified maximum execution timeout.
> 	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:232)
> 	... 12 more
> 2018-06-04 05:34:55,611 WARN  [pool-2-thread-6] n.e.a.e.c.r.ErrorNotificationHandler - Received general error notification during stealing lease on partition N/A: The client could not finish the operation within specified maximum execution timeout.

## Expected Behavior
Not losing the lease or quickly reacquiring it. 

## Versions  
- OS platform and version: Debian 8
- Maven package version or commit ID: 1.0.0

**Comment by JamesBirdsall** [comment]
If a processor instance is experiencing errors accessing the shared lease store up in Azure Storage such that it cannot renew a lease, it may not be able to reacquire the lease either for the same reason.

Errors such as these are logged at a high priority because they are errors. Successfully acquiring a new lease is the happy path and right now is logged at DEBUG level. We can consider bumping it up to INFO.

**Comment by royyeah** [comment]
Thanks for your clear explanation - I would vote for logging it at INFO level since there is no way to see from the logs whether it is reacquired. 
 
Also I noticed EventProcessor.onClose() was not called when the lease was lost - why is this? I would expect the processing of this partition would stop in this case.
