### ISSUE TITLE
How EventProcessorHost achieve load balancing among many running instances

### ISSUE THREAD

**Issue by warrenzhu25** [Azure/azure-event-hubs-java#338]
1. If I register a processor with an event hub which has 3 partitions. Will 3 threads be created for each partiton?
2. If I register another processor in the same consumer group but the different hostNamePrefix? It should balance 3 partitions between these processors. How this happen? If the previous one already hold the lease, how current one get it?

## Versions  
- azure-eventhubs-eph 1.0.0

**Comment by JamesBirdsall** [comment]
1) No. Earlier versions had one long-running thread per partition, and a threadpool. Starting with 1.0.0, everything is in the threadpool.
2) Balancing between processor instances requires that they use the same Azure Storage information: Storage account, container name, and blob prefix if used. This shared store is where lease and checkpoint information is kept.

**Comment by SreeramGarlapati** [comment]
If you need further help to understand how `EPH` lease stealing from other Processor instances work - please refer to our recommended reads on web:
[DAN's blog](https://blogs.msdn.microsoft.com/servicebus/2015/01/21/event-processor-host-best-practices-part-2/)
[Explanation in SO](https://stackoverflow.com/a/41867611/3277385)
