### ISSUE TITLE
eventhub MessagingFactory issue

### ISSUE THREAD

**Issue by ccmehk** [Azure/azure-event-hubs-java#350]
i have experienced this issue for the eventhub 1.0.2, and the connection is lost, please check

[pool-7-thread-11] WARN com.microsoft.azure.eventhubs.impl.MessagingFactory - messagingFactory[MessagingFactoryec09cd], hostName[XXX.servicebus.windows.net], error[Unhandled exception while processing events in reactor, report this error.
java.lang.NullPointerException: uncorrelated channel: 0
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:292)
com.microsoft.azure.eventhubs.impl.MessagingFactory$RunReactor.run(MessagingFactory.java:483)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)Cause: uncorrelated channel: 0
org.apache.qpid.proton.engine.impl.TransportImpl.handleBegin(TransportImpl.java:1155)
org.apache.qpid.proton.engine.impl.TransportImpl.handleBegin(TransportImpl.java:67)
org.apache.qpid.proton.amqp.transport.Begin.invoke(Begin.java:144)
org.apache.qpid.proton.engine.impl.TransportImpl.handleFrame(TransportImpl.java:1396)
org.apache.qpid.proton.engine.impl.FrameParser.input(FrameParser.java:418)
org.apache.qpid.proton.engine.impl.FrameParser.process(FrameParser.java:527)
org.apache.qpid.proton.engine.impl.SaslImpl$SwitchingSaslTransportWrapper.process(SaslImpl.java:805)
org.apache.qpid.proton.engine.impl.HandshakeSniffingTransportWrapper.process(HandshakeSniffingTransportWrapper.java:101)
org.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.unwrapInput(SimpleSslTransportWrapper.java:135)
org.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.process(SimpleSslTransportWrapper.java:361)
org.apache.qpid.proton.engine.impl.ssl.SslImpl$UnsecureClientAwareTransportWrapper.process(SslImpl.java:144)
org.apache.qpid.proton.engine.impl.TransportImpl.process(TransportImpl.java:1507)
org.apache.qpid.proton.reactor.impl.IOHandler$1.run(IOHandler.java:233)
org.apache.qpid.proton.reactor.impl.SelectableImpl.readable(SelectableImpl.java:118)
org.apache.qpid.proton.reactor.impl.IOHandler.handleQuiesced(IOHandler.java:60)
org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:389)
org.apache.qpid.proton.engine.BaseHandler.onReactorQuiesced(BaseHandler.java:87)
org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:206)
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:292)
com.microsoft.azure.eventhubs.impl.MessagingFactory$RunReactor.run(MessagingFactory.java:483)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)]

## Versions  
- OS platform and version: redhat
- Maven package version or commit ID: eventhub 1.0.2

**Comment by ccmehk** [comment]
remark: i am using proton-j-0.27.1

**Comment by ccmehk** [comment]
Also, i think this is related to the following issue:
https://github.com/Azure/azure-event-hubs-java/issues/103
https://github.com/Azure/azure-event-hubs-java/issues/204
https://github.com/Azure/azure-event-hubs-java/issues/287
thanks

**Comment by SreeramGarlapati** [comment]
A session timed out and the client closed it and later - after a while - service responds with session.Begin. In this scenario - proton-j framework is not ready to handle this and throws a `NullPointerException`.

They have a todo to fix this - please file a JIRA issue on them to get this issue fixed:

https://github.com/apache/qpid-proton-j/blob/3e59d10d65f0206ddcd75be59749d28aab17402c/proton-j/src/main/java/org/apache/qpid/proton/engine/impl/TransportImpl.java#L1160

**Comment by SreeramGarlapati** [comment]
This issue is already being tracked in #287.
