### ISSUE TITLE
IOT Hub Support

### ISSUE THREAD

**Issue by heynevets** [Azure/azure-event-hubs-java#352]
## Actual Behavior
1. In order to connect to the event hubs endpoint of an IoT Hub, user has to prepare the EH endpoint string and path string in addition to the IoT Hub connection string
2. There are already supporting functions in Python and Node released by MS. see this: https://github.com/Azure/azure-event-hubs-python/issues/28
The way they did it is to get the redirect error message from the server and parse the EH connection string from it

## Expected Behavior
1. User should be able to connect to the event hub endpoint of an IoT Hub with solely the IoT Hub connection string in Java as well
2. MS should release the java version of "EventHubsClient.fromIoTConnectionString(connectionString)" too

## Versions  
- OS platform and version: Windows 10
- Maven package version or commit ID: 
            <groupId>com.microsoft.azure.sdk.iot</groupId>
            <artifactId>iot-service-client</artifactId>
            <version>1.14.0</version>

**Comment by jatinv-c** [comment]
Any ETA on this feature ?

**Comment by tmb-twx** [comment]
Is there any ETA for this?   The IoT Hub documentation states that we need to use the IoT Hub connection string to seamlessy support hub failover and disaster recovery. (https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-ha-dr).  It would be nice if the Java event hub SDK was capable of this.

**Comment by JamesBirdsall** [comment]
This repo is obsolete, and the Event Hubs client which lived here is now regarded as legacy and we are not adding features. The new EH Java client can be found at https://github.com/Azure/azure-sdk-for-java/ -- if you open this issue there and tag it "Event Hubs", the people who can answer your question will see it. Thanks!

**Comment by conniey** [comment]
https://github.com/Azure/azure-sdk-for-java/issues/18514 represents this issue.
