### ISSUE TITLE
Build on Appveyor is failing due to Maven config issue

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-event-hubs-java#359]
Please refer to the console output presented here: https://ci.appveyor.com/project/sabeegrewal/azure-event-hubs-java/branch/master

I note that the dependency on Maven is set to be http://www.us.apache.org/dist/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.zip in the master branch, which no longer exists, but that this has been incremented to 3.5.4 in the dev branch, which does work. Perhaps the master branch could have this fix applied to the appveyor file?

**Comment by JamesBirdsall** [comment]
This will be merged to master as part of the EPH 2.0.1 release, hopefully today.

**Comment by JamesBirdsall** [comment]
This is now in main via PR #357

**Comment by JonathanGiles** [comment]
Perfect, thanks!
