### ISSUE TITLE
[Question] Is the number of IEventProcessor instance equals number of partition

### ISSUE THREAD

**Issue by warrenzhu25** [Azure/azure-event-hubs-java#367]
According to comments of `IEventProcessor`

> Any given instance of an event processor class will only process events from one partition of one Event Hub.

Does this mean that we have same number of `IEventProcessor` instance created as partition?

**Comment by JamesBirdsall** [comment]
Yes. If there are P partitions and H cooperating instances of EventProcessorHost, then each host instance will have about P/H instances of IEventProcessor, and the total number of IEventProcessor instances across all hosts will be P.
