### ISSUE TITLE
PartitionReceiver is getting blocked while receiving message from event hub

### ISSUE THREAD

**Issue by singhania** [Azure/azure-event-hubs-java#371]
Hi,
I am using Eventhub 1.0.0 version with EPH 1.0.0 version and encounter an issue.
Actual Behaviour
Threads which are receiving the messages from EventHub are getting blocked and EPH is not able to send any messages to EventProcessor. 
Expected Behaviour
It should not get blocked and EPH should able to send messages to Processor.

Versions  
OS platform and version: Ubuntu
Maven package version or commit ID:
Eventhub : 1.0.0 (java sdk)
Event Processor Host :  1.0.0 (java sdk)

Attached is the thread dump for analysis.
[file.txt](https://github.com/Azure/azure-event-hubs-java/files/2309538/file.txt)

**Comment by SreeramGarlapati** [comment]
Hi @singhania

Thread dump would show up as Receivers waiting for receiving messages. That's completely normal.

If you want `IEventProcessor.onEvents` callback to be invoked for you to know that the Receiver pipeline is Healthy - use the flag: `EventProcessorOptions.setInvokeProcessorAfterReceiveTimeout(true)` to get notified on every receive call - even if no events are received.

alternatively, use these strategies to debug the issue:

1) if the EventHubs partition on which your receiver is receiving - doesn't have any messages - then - `EPH` processor wouldn't be invoked. To findout if there are messages ready to be consumed use EventHub `partitionRuntimeInformation` API.

2) If the messages are present and you are unable to receive the messages, then:
- enable warn logs on event hubs java client package (`com.microsoft.azure.eventhubs`)- which can help understand - if there are any errors going on with the receiver. Those errors should lead you with troubleshooting the problem.
- if you don't find any errors/warning in the logs - go one level deeper & understand if there is  any n/w'ing issue with connecting to EventHubs service (enabling wireshark traces - can certainly help here).

The issue you filed is very generic in nature. Please add clear steps on how to reproduce the problem so, we will be able to address...

**Comment by SreeramGarlapati** [comment]
please definitely reopen the issue - if you need more help. We are here to help - but, as I mentioned above - we need more info here to be able to help... please feel free to open a support ticket - if you need more direction: https://azure.microsoft.com/en-us/support/options/
