### ISSUE TITLE
Client creation hangs

### ISSUE THREAD

**Issue by acurvers** [Azure/azure-event-hubs-java#386]
on A Java EE wildfly 10.
EventHubClient.createSync(connectionString, MY_NO_RETRY, executor);
this method never returns on a certain Wildfly instance, while another instance does not have any problem with it.
To resolve it I tied different executors, like managed ones and custom thread excutors but the createSync method just never returns not even after maybe an expected timeout. Not sure how to troubleshoot this

## Versions  
- OS platform and version: Linux CentOS
- Maven package version or commit ID: 1.2

**Comment by sjkwak** [comment]
Hi @acurvers, as Sreeram suggested, please try enabling frame traces and debug the issue. And, if needed, please reopen the issue.
