### ISSUE TITLE
Make it possible to checkpoint outside an IEventProcessor

### ISSUE THREAD

**Issue by janbols** [Azure/azure-event-hubs-java#387]
## Actual Behavior
Currently checkpointing can only be done by calling the `PartitionContext.checkpoint` method. The `PartitionContext` is only available inside the `onEvents` method of an `IEventProcessor` or in the `IEventProcessorFactory`. This means that the checkpointing must be done inside of the `onEvents` method.

## Expected Behavior
It would be nice to be able to do checkpointing outside the event handler. This would make it easier to use the event processor host in a reactive streaming application where events are received and passed through a stream (f.e. in rxJava or AkkaStreams) and finally checkpointed further down the stream. 

This would decouple the consumption of the events from checkpointing them, however in the curent setup there's no way of doing that.

## Versions  
- azure-eventhubs-eph:2.0.1

**Comment by warrenzhu25** [comment]
Also need this feature.

**Comment by ramya-rao-a** [comment]
@conniey Is this possible to do in the newer azure-messaging-eventhubs Java library?

**Comment by conniey** [comment]
Yes. When you create EventProcessorClient via [`EventProcessorClientBuilder`](https://azuresdkdocs.blob.core.windows.net/$web/java/azure-messaging-eventhubs/5.7.0/com/azure/messaging/eventhubs/EventProcessorClientBuilder.html#checkpointStore-com.azure.messaging.eventhubs.CheckpointStore-), you have to pass in a [CheckpointStore](https://azuresdkdocs.blob.core.windows.net/$web/java/azure-messaging-eventhubs/5.7.0/com/azure/messaging/eventhubs/CheckpointStore.html).   This store exposes `updateCheckpoint(Checkpoint)`, which you can invoke outside of the EventProcessorClient.

**Comment by JamesBirdsall** [comment]
This client is now legacy and in maintenance mode. We will not be adding new features. You can find the new Java Event Hubs client at https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/azure-messaging-eventhubs , and this feature is already present there.
