### ISSUE TITLE
Unable to pass RetryPolicy to EventProcessorHost constructor with AzureStorageCheckpoint

### ISSUE THREAD

**Issue by sergey-ua** [Azure/azure-event-hubs-java#388]
## Actual Behavior
EventProcessorHost has only one constructor which accepts RetryPolicy:
```
EventProcessorHost(
            final String hostName,
            final String eventHubPath,
            final String consumerGroupName,
            final String eventHubConnectionString,
            ICheckpointManager checkpointManager,
            ILeaseManager leaseManager,
            ScheduledExecutorService executorService,
            RetryPolicy retryPolicy)

```
As you can see I need to pass  `ICheckpointManager` and `ILeaseManager`, but in case I want to reuse built-in implementation `AzureStorageCheckpointLeaseManager` I can't do it, because it is non-public class with package-level constructor.

## Expected Behavior
`EventProcessorHost` should have additional constructor overload where it is possible to pass RetryPolicy, ScheduledExecutorService and use Azure Storage checkpointing/leasing

## Versions  
- OS platform and version: MacOs
- Maven package version or commit ID: azure-eventhubs-eph: 2.0.1

**Comment by janbols** [comment]
Even when `AzureStorageCheckpointLeaseManager ` would have a public constructor, it would still not work correctly b/c there's custom code in the `EventProcessorHost` that's only executed when coming from the constructor with the storage connection strings. 
Frankly, I think the way everything is initialized is confusing, error prone and only usable using the regular constructor, so perhaps a refactoring or redesign is in place.

**Comment by sergey-ua** [comment]
Also saw that custom code. Agree that refactoring is needed there. At least move creation of `EventProcessorHost` to builder or so. 

But as of now, impossibility of usage retry strategy and azure storage checkpointing together sounds ridiculous. Not voting against redesign, but simply adding another constructor overload would  unblock significant functional part of SDK.

**Comment by JamesBirdsall** [comment]
Originally there was a logical progression of constructors from simple to complex but now many things have been bolted on which are orthogonal to each other and could be used in many different combinations. Some of them may need to be constructor settings and could be added to an existing settings object, while others could be combined into a new settings object. Adding new, redesigned constructors and deprecating certain old ones should be fairly simple and won't be a breaking change for anyone right away. It's something we should consider for the next release.

**Comment by ramya-rao-a** [comment]
In the newer `azure-messaging-eventhubs` Java library, you get to create the storage client separately with its own set of retry options than the event processor. Please take a look at this sample: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/src/samples/java/com/azure/messaging/eventhubs/checkpointstore/blob/EventProcessorWithAzureIdentity.java

**Comment by JamesBirdsall** [comment]
EventProcessorHost is now a legacy client in maintenance mode and we will not adding features.
