### ISSUE TITLE
PartitionReceiver.setPrefetchCount - API, in few cases leads to zero prefetch count

### ISSUE THREAD

**Issue by yarinm** [Azure/azure-event-hubs-java#389]
## Actual Behavior
In my deployment after about 1 hour of processing of a specific partition receiver we close it and its client and re-create them (we wait for the close futures to end before we do that)
It seems that occasionally some partition receivers right after creation their receive is stuck for 30 minutes. The receiver crashes after getting the following exception from the service:
"linkName[058405_5e9_G26_1540185953630], ErrorCondition[amqp:link:detach-forced, The link 'G26:350217988:058405_5e9_G26_1540185953630' is force detached by the broker due to errors occurred in consumer(link10672072). Detach origin: AmqpEventHubConsumer.IdleTimerExpired: Idle timeout: 00:30:00. TrackingId:f5fd0f86000134e800a2d7c85bcd5f61_G26_B9, SystemTracker:cas-prod03-use2-pipeline1-primary:eventhub:activitypipeline0~19455|anubis, Timestamp:10/22/2018 6:00:16 AM]"

This behavior started after upgrading to 1.X, before that we were using 0.4.5 I tried to recently upgrade from 1.0.2 to 1.2.0 but the problem still persists
Our EventHubs have high generation rate and consumption rate, not sure if this is relevant.

I also noticed that 1.0.2 Should've solved some issue with prefetch count. 
And the issue that was solved in 1.2.0 https://github.com/Azure/azure-event-hubs-java/issues/377 Also looked promising but didn't solve it.

I also tried to reproduce it on a small dev EventHub but I couldn't do it.

I'll try to send you over some of the client's logs later today.

## Versions  
- Ubuntu 14
- SDK version 1.2.0

**Comment by yarinm** [comment]
[eh_logs.txt](https://github.com/Azure/azure-event-hubs-java/files/2502468/eh_logs.txt)
I've marked on the log file the events as the occurred, the time of the exception, when we closed and recreated the partition receiver and client.

The relevant eventhub (that was stuck) is activitypipeline1/ConsumerGroups/AnubisMirror/Partitions/1

**Comment by yarinm** [comment]
With the help of @SreeramGarlapati, we've discovered the calling setPrefetchCount after PartitionReceiver creation can cause this behaviour. For now the workaround is to not call the method.

@SreeramGarlapati will provide a fix for that in a few weeks

**Comment by SreeramGarlapati** [comment]
@Sjkwak - fixed this as part of #410.. 
SetPrefetchCount API is moved out to receiver creation time Options class - which removes the chance of race condition that we are currently hitting. Thanks a lot for filing this issue and persistently following up with required logs and traces @Yarinm; this helped us step up the library quality...
