### ISSUE TITLE
Performance testing benchmark of event hub java sdk

### ISSUE THREAD

**Issue by warrenzhu25** [Azure/azure-event-hubs-java#396]
Do we have some performance benchmark related with produce, consume with PartitionReceiver or EPH? Or some tools to help do this kind of test?

**Comment by conniey** [comment]
We have an issue to create performance tests to compare both Track 1 and Track 2
https://github.com/Azure/azure-sdk-for-java/issues/20791

**Comment by JamesBirdsall** [comment]
This client is now legacy and in maintenance mode. You can find the new Java Event Hubs client at https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/azure-messaging-eventhubs
