### ISSUE TITLE
MessageSender and ReplayableWorkItem are not thread-safe but got accessed from various threads

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs-java#4]
_From @ialexandrov on October 21, 2016 11:32_

 MessageSender has set of fields which are not final.  At the same time methods of MessageSender are called from different threads without any state synchronization. This will lead to ocasional phantom isssues. 
Either make MessageSender thread safe or make sure all members of it are only accessed from reactor thread,

For example:
MessageSender.lastKnownLinkError is set by reactor thread in onError method and read in sendCore() method which is called from ForJoinPool due to (probably) bug in EventHubClient.send(..,) methods where **thenComposeAsync is called instead on thenCompose.**

More of less the same problem is with ReplayableWorkItem.lastKnownException which is again is set by reactor thread but read from timer thread pool thread:

java / azure-eventhubs / src / main / java / com / microsoft / azure / servicebus / MessageSender.java 
`778                    MessageSender.this.throwSenderTimeout(sendData.getWork(), sendData.getLastKnownException());`

_Copied from original issue: Azure/azure-event-hubs#284_

**Comment by SreeramGarlapati** [comment]
@ialexandrov
- thanks a lot for the valuable suggestion.
You are first one (and infact the only one so far) to understand the threading model of eventhubs javaclient without me explaining it :) - this awe'd me.

Please see if the PR #93 addresses the feedback you have (sorry about the delay)...

**Comment by jtaubensee** [comment]
Closing based on PR #93
