### ISSUE TITLE
Improve documentation on exceptions

### ISSUE THREAD

**Issue by jsiegmund** [Azure/azure-event-hubs-java#405]
We are using the service bus SDK from a Java based application. We were getting exceptions and we're in the process of debugging those. The exception message includes the following information: 

> LAST_OFFSET: 2240952, PREFETCH_COUNT: 999, LINK_CREDIT: 992, PREFETCH_Q_LEN: 0, R_TYPE: EPOCH

We'd like more information about what these mean in order to be able to interpret them, but a Google search actually pointed us to an issue in this repo. So hereby opening up an issue to request documentation on these items, either within this ticket (for now it'll probably be found :)) or on docs.microsoft.com of course. If in the meantime anyone can enlighten us, that would be great!

**Comment by conniey** [comment]
We have an issue open for Track 2 to improve this experience:
https://github.com/Azure/azure-sdk-for-java/issues/20837
and
https://github.com/Azure/azure-sdk-for-java/issues/3806

**Comment by JamesBirdsall** [comment]
This client is now legacy and in maintenance mode. You can find the new Java Event Hubs client at https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/azure-messaging-eventhubs
