### ISSUE TITLE
How many java threads are created

### ISSUE THREAD

**Issue by prasada2** [Azure/azure-event-hubs-java#409]
## Actual Behavior
There are 29 partitions on the event hub which i am accessiong jusing java implementation 
of Eventprocesser and IEventProcessor and i see that there are around 8/9 java threads being created and roundrobined to the 29 partions

## Expected Behavior
Are we expected to have same number of threads created as the number of partitions

## Versions  
- OS platform and version:
- Maven package version or commit ID:

**Comment by JamesBirdsall** [comment]
Event Processor Host and the event hub client is it built on do not have dedicated, long-running threads anymore. Everything is a task that is executed in a thread pool/executor service. Event Processor Host creates a default pool with 16 threads if the user doesn't supply one to the constructor. It should run even with a one-thread pool, although performance will be lower. Performance is the main reason to have more threads, especially if your IEventProcessor.OnEvents implementation takes a significant amount of time to execute. But if you see threads in the pool which are parked waiting for tasks to execute, then you probably have enough.
