### ISSUE TITLE
support for ManagedServiceIdentityTokenProvider

### ISSUE THREAD

**Issue by rkrashr** [Azure/azure-event-hubs-java#412]
## Actual Behavior
1. RBAC for Event Hubs is supported, based on documentation
https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-role-based-access-control

2. RBAC is supported in Azure Portal UI

3. RBAC is supported in similar c# library (azure-event-hibs-dotnet repo)

Currently, in java only Policy name + key authentication is supported

## Expected Behavior
MSI token authentication can be used to access event hubs in java for sending and receiving events

Another benefit (and this is what we need, and our customers request):
When running in Azure cloud, authentication for services is VM identity-based. This way it is much easier to manage.

## Versions  
- OS platform and version: Linux RedHat 
Linux 4.15.0-1035-azure x86_64
- Maven package version or commit ID:

**Comment by jefjos** [comment]
Is there an ETA for this? What is the workaround for this?

**Comment by JamesBirdsall** [comment]
There isn't a workaround, but we are actively working on adding RBAC support to the Java client and expect to release in the next few weeks.

**Comment by pankajisgarg** [comment]
Is there an ETA for making this feature GA.

**Comment by boybundit** [comment]
According to the latest example [here](https://github.com/Azure/azure-event-hubs/tree/master/samples/Java/Rbac), it seems that this feature is already implemented?

**Comment by JamesBirdsall** [comment]
You are correct. The Event Hubs Java client migrated to another repo https://github.com/Azure/azure-sdk-for-java/ at the time we released the RBAC support, and it looks like we missed cleaning up this issue in this old repo.
