### ISSUE TITLE
How to get the connection string for ADLS Gen 1?

### ISSUE THREAD

**Issue by dchoong** [Azure/azure-event-hubs-java#413]
Previously, when developing for blob storage, we were able to use the EventHub connection string in EventProcessorHost to access the storage. However, with ADLS Gen 1, there doesn't seem to be such a string, and we're having trouble finding any classes that allows us to connect to ADLS. The authentication system seems to be completely different. How can we connect to the ADLS Gen 1 storage using the EventHostProcessor.java?

**Comment by sjkwak** [comment]
Hi @dchoong, using EventProcessorHost with ADLS Gen 1 is not a supported scenario.
