### ISSUE TITLE
Using Azure Event Hubs in Android Studio

### ISSUE THREAD

**Issue by redraven984** [Azure/azure-event-hubs-java#42]
Hi All,

I am new at building Android Applications. In my first application I would like to push data to an Azure event hub. I have read the tutorial here: https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-java-ephcs-getstarted

In Android studio I added azure-eventhubs-0.10.0.jar and then added it as a library to the project. Unfortunately, when testing the app this leads to a build error: 

Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.

In response I added the lines:
targetCompatibility = '1.7'
sourceCompatibility = '1.7'

to build.gradle but the error remains. I think I am not correctly adding the azure event hub library to android studio. Can someone explain to me how to add maven repositories in android studio?

**Comment by redraven984** [comment]
Update, I believe you add dependencies by adding them to the build.gradle file. Here is my project build.gradle which produces the same error:

apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.example.applicationv1"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

    }
    compileOptions {
        targetCompatibility JavaVersion.VERSION_1_7
        sourceCompatibility JavaVersion.VERSION_1_7
    }

    packagingOptions {
        exclude 'META-INF/NOTICE' // will not include NOTICE file
        exclude 'META-INF/LICENSE' // will not include LICENSE file
    }

}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.1.0'
    testCompile 'junit:junit:4.12'
    // https://mvnrepository.com/artifact/com.microsoft.azure/azure-eventhubs-eph
    compile 'com.microsoft.azure:azure-eventhubs-eph:0.10.0'
    compile group: 'com.google.code.gson', name: 'gson', version: '2.8.0'

}

**Comment by redraven984** [comment]
Update: It looks like if I enable jack and java 1.8 then I can move past the DEX error, however I have a new error which suggests the lambda function cannot be used from the Android device. 

Error:Pump.java:73-74: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.lang.Runnable
Error:PartitionManager.java:259-260: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.concurrent.Callable
Error:PartitionManager.java:268-269: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.concurrent.Callable
Error:AzureStorageCheckpointLeaseManager.java:139-140: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.concurrent.Callable
Error:AzureStorageCheckpointLeaseManager.java:230-231: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.concurrent.Callable
Error:AzureStorageCheckpointLeaseManager.java:236-237: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.concurrent.Callable
Error:AzureStorageCheckpointLeaseManager.java:296-297: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.concurrent.Callable
Error:AzureStorageCheckpointLeaseManager.java:369-370: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.concurrent.Callable
Error:AzureStorageCheckpointLeaseManager.java:433-434: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.concurrent.Callable
Error:AzureStorageCheckpointLeaseManager.java:501-502: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.concurrent.Callable
Error:AzureStorageCheckpointLeaseManager.java:159-160: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.concurrent.Callable
Error:com.android.jack.JackAbortException
Error:Execution failed for task ':app:transformClassesWithPreJackPackagedLibrariesForDebug'.
> com.android.build.api.transform.TransformException: com.android.jack.api.v01.CompilationException

**Comment by JamesBirdsall** [comment]
Does Android have a Java 8 runtime, or only Java 7? Our Java Event Hub Client and Java Event Processor Host have a hard requirement for Java 8.
