### ISSUE TITLE
Update Examples to Use Latest Version in Maven (2.2.0)

### ISSUE THREAD

**Issue by lreading** [Azure/azure-event-hubs-java#425]
The [azure-event-hubs README](https://github.com/Azure/azure-event-hubs) says "If you have any feedback, questions, or comments, go to the respective repo and file an issue," which is why I'm opening an issue here.

The Java samples are using old versions of the azure-event-hubs package.  They should be updated to reflect how to use the latest version (currently 2.2.0):
 - [AdvancedSendOptions](https://github.com/Azure/azure-event-hubs/blob/master/samples/Java/Basic/AdvancedSendOptions/pom.xml#L50) is using 1.0.1
 - [EventProcessorSample](https://github.com/Azure/azure-event-hubs/blob/master/samples/Java/Basic/EventProcessorSample/pom.xml#L50) is using 1.0.0
 - [ReceiveByDateTime](https://github.com/Azure/azure-event-hubs/blob/master/samples/Java/Basic/ReceiveByDateTime/pom.xml#L50) is using 1.0.0
 - [ReceiveUsingOffset](https://github.com/Azure/azure-event-hubs/blob/master/samples/Java/Basic/ReceiveUsingOffset/pom.xml#L50) is using 1.0.0
 - [ReceiveUsingSequenceNumber](https://github.com/Azure/azure-event-hubs/blob/master/samples/Java/Basic/ReceiveUsingSequenceNumber/pom.xml#L50) is using 1.0.0
 - [SendBatch](https://github.com/Azure/azure-event-hubs/blob/master/samples/Java/Basic/SendBatch/pom.xml#L50) is using 1.0.0
 - [SimpleSend](https://github.com/Azure/azure-event-hubs/blob/master/samples/Java/Basic/SimpleSend/pom.xml#L50) is using 1.2.0

**Comment by sjkwak** [comment]
Thanks @lreading, we will update the samples.

**Comment by JamesBirdsall** [comment]
I was working on a related area so I made these changes. See https://github.com/Azure/azure-event-hubs/pull/436

**Comment by JamesBirdsall** [comment]
The PR is merged.

@lreading Thanks for the reminder. I have added "update samples" to our client release checklist, so this shouldn't happen again.
