### ISSUE TITLE
Running azure event hubs in integration tests

### ISSUE THREAD

**Issue by Danondso** [Azure/azure-event-hubs-java#426]
I've been having quite a time trying to setup up event hub to run in an integration test (I'm running my tests with SpringRunner). Based on what I've tried so far it seems like the only way to connect is to always reach out and connect to a real event hub. Has anyone been able to get these mocked up successfully to run during tests? And if not, is there any way to make azure-event-hubs-java more friendly to integration testing?

**Comment by JamesBirdsall** [comment]
See my comments on #433 . Since the two issues are essentially identical, I'm going to close this one, but thank you for bringing it up! The more user demand there is, the more likely that the work will actually happen.
