### ISSUE TITLE
Maximum size of Event Hubs event changed to 1MB

### ISSUE THREAD

**Issue by adoelger** [Azure/azure-event-hubs-java#430]
## Actual Behavior
1. Definition in the class "com/microsoft/azure/eventhubs/impl/ClientConstants.java" MAX_MESSAGE_LENGTH_BYTES = 256 * 1024;
2. Limits event hubs event size to 256kb.

## Expected Behavior
1. Maximum size of Event Hubs event was changed to 1MB.
2. see: https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-quotas

## Versions  
- OS platform and version:
- Maven package version or commit ID:

**Comment by JamesBirdsall** [comment]
That is the default maximum size, which has to remain at 256KB until we finish rolling out the change worldwide. If you look at MessageSender.onOpenComplete, you will see code that queries the Event Hubs cluster at runtime and updates with the maximum that the cluster supports. We have not had reports of large events failing, so we believe that code is working as designed. If you have having trouble sending events larger than 256KB to a cluster which should support those events, let us know and we will investigate further.

**Comment by adoelger** [comment]
Okay, thank you!

**Comment by rsethur** [comment]
Hello @JamesBirdsall ,
I'm having trouble sending a 330k message. I'm using East US.
Any pointers here, please?

EventHubError: The received message (delivery-id:0, size:327545 bytes) exceeds the limit (262144 bytes) currently allowed on the link. TrackingId:de96150b-bac4-4606-9575-b363ae7518e8_B3, SystemTracker:NoSystemTracker, Timestamp:2019-04-28T12:25:34
ErrorCodes.LinkMessageSizeExceeded: The received message (delivery-id:0, size:327545 bytes) exceeds the limit (262144 bytes) currently allowed on the link. TrackingId:de96150b-bac4-4606-9575-b363ae7518e8_B3, SystemTracker:NoSystemTracker, Timestamp:2019-04-28T12:25:34

**Comment by JamesBirdsall** [comment]
@rsethur What is your billing tier? Basic only supports 256K. If that's not the issue, tell me your namespace and I can take a look.
