### ISSUE TITLE
Unable to connect producer code to the azure event hub with simplesend.java code

### ISSUE THREAD

**Issue by SANDEEPPILLUTLA** [Azure/azure-event-hubs-java#436]
## Actual Behavior
1. able to connect to azure event hub
2. 

## Expected Behavior
1. connection refused
2. 

## Versions  
- OS platform and version: Mac
- Maven package version or commit ID:

**Comment by sjkwak** [comment]
Hi @SANDEEPPILLUTLA, can you please provide some more context about the issue?

**Comment by basilhariri** [comment]
Closing due to not enough info / inactivity.
