### ISSUE TITLE
Checkpointing not compatible between .NET and Java version of library

### ISSUE THREAD

**Issue by alexnorth** [Azure/azure-event-hubs-java#442]
## Actual Behavior
1. Checkpoint data from EventProcessor with .NET version of library is not properly parsed by Java version of library
2. Checkpoint data from EventProcessor with Java version of library is not properly parsed by .NET version of library

## Expected Behavior
1. The checkpoint file should be manageable by any language version of the library

## Versions  
- Maven package version or commit ID: java azure-eventhubs-eph 2.5.0

I have an application in .NET that uses the azure event hub library, which implements IEventProcessor and creates a checkpoint file.  Same checkpoint file is used by application at startup and for making further checkpoints without any problems.

I then stop the application and run a tool developed in Java to eat up any remaining events (this is for "clearing" the event hub for testing purposes to make sure that there are no events consumed from a previous run upon startup).  The checkpoint data is not parsed correctly in the Java side and then the object defaults for AzureBlobLease are used when making a checkpoint (eg: sequenceNumber = 0, partitionId = -1).

The reason appears to be down to the Json parsing and Pascal-case vs Camel-case.

A sample file created from the .NET library:
`{"PartitionId":"4","Owner":"xxxxxxxx-yyyy-zzzz-aaaa-bbbbbbbbbbb","Token":"abccd560-7908-41e3-93f7-351d64b81xyz","Epoch":48,"Offset":"21477944736","SequenceNumber":39605}`

And after the Java library has checkpointed it:
`{"sequenceNumber":0,"token":"abccd560-7908-41e3-93f7-351d64b81xyz","epoch":22,"partitionId":"-1","owner":"xxxxxxxx-yyyy-zzzz-aaaa-bbbbbbbbbbb"}`

For my own purposes I can get around the problem by downloading of the file from the blob and parse with Gson into own simple class (as I have to skip the checkpointing feature and related classes from the library).  To do this and parse the json properly I can use
`
        GsonBuilder gsonBuilder = new GsonBuilder();
        gsonBuilder.setFieldNamingPolicy(FieldNamingPolicy.UPPER_CAMEL_CASE);
        Gson gson = gsonBuilder.create();
`
This is not a good solution at library level as it will break one side or the other, this is just for my current case.

**Comment by conniey** [comment]
In track 2, we ensured that checkpoints are compatible cross language (ie. Java, .NET, Python, and TS/JS)

**Comment by JamesBirdsall** [comment]
EventProcessorHost for both Java and .NET are now legacy clients in maintenance mode. We will not be adding new features.
