### ISSUE TITLE
Support http/1.0 proxy instead of 1.1 only

### ISSUE THREAD

**Issue by jugi92** [Azure/azure-event-hubs-java#445]
## Actual Behavior
1. The proton library used for network transport only supports http/1.1 proxy because of the follwing line: 
https://github.com/Azure/qpid-proton-j-extensions/blob/master/src/main/java/com/microsoft/azure/proton/transport/proxy/impl/ProxyHandlerImpl.java#L50

## Expected Behavior
1.  http/1.0 proxy should also be possible to use for the transport, so in some cases the proxy requests http/1.1 proxy but the proxy returns "HTTP/1.0 200 Connection established"

## Versions  
- Maven package version or commit ID: 2.3.0

**Comment by jugi92** [comment]
This should be solved by this commit: https://github.com/Azure/qpid-proton-j-extensions/pull/19

**Comment by jugi92** [comment]
It would be nice if a release with this fix would be planned soon

**Comment by JamesBirdsall** [comment]
This change was merged into qpid-proton-j-extensions and released with version 1.2.2, which was first used by client release 3.1.1.
