### ISSUE TITLE
eph 2.4.0 not working with azure storage 11

### ISSUE THREAD

**Issue by warrenzhu25** [Azure/azure-event-hubs-java#450]
Please refer https://github.com/microsoft/spring-cloud-azure/issues/517

* spring-cloud-azure-eventhubs-stream-binder (1.1.0.RC4) used azure-azure-eventhubs-eph(2.4.0)
* azure-storage-blob (11.0.0)

And the below exception is throw:
`com.microsoft.azure.storage.blob.BlobRequestOptions\"'s signer information does not match signer information of other classes in the same package`

**Comment by JamesBirdsall** [comment]
Yes, Event Processor Host requires a Storage 8.x client.

This client is now legacy and in maintenance mode. We will not be making major changes. You can find the new Java Event Hubs client at https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/azure-messaging-eventhubs
