### ISSUE TITLE
Failure to recover from network interruption in eph

### ISSUE THREAD

**Issue by warrenzhu25** [Azure/azure-event-hubs-java#452]
Somebody reports this issue https://github.com/microsoft/spring-cloud-azure/issues/537. And exception is thrown from EPH. Could you help take a look

**Comment by JamesBirdsall** [comment]
The linked issue is closed.

In any case, this client is now legacy and in maintenance mode. You can find the new Java Event Hubs client at https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/azure-messaging-eventhubs , and there are new Spring binders for the new client.
