### ISSUE TITLE
Client side logging sent messages

### ISSUE THREAD

**Issue by c4rlosmarin** [Azure/azure-event-hubs-java#457]
Just reaching out to check if there is a way to log information about sent messages as soon as the SendSync method is call, e.g., Reference ID /Tracking ID generated by the client.

**Comment by JamesBirdsall** [comment]
There's an ID generated for the send activity, but the client doesn't expose that programmatically -- it's only visible in client-side tracing if you turn that on. If you're looking to track a message through the system, then putting an ID into a property is the best way to go, with the downside that it's not visible in our service-side logs. We are aware that end-to-end tracing of messages is a weak spot.

In any case, this client is now legacy and in maintenance mode. We will not be adding new features. You can find the new Java Event Hubs client at https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/eventhubs/azure-messaging-eventhubs
