### ISSUE TITLE
Azure eventhub Kafka org.apache.kafka.common.errors.TimeoutException for some of the records

### ISSUE THREAD

**Issue by prakashse7en** [Azure/azure-event-hubs-java#458]
## Actual Behavior
1. Have a ArrayList containing 80 to 100 records trying to stream and send each individual record(POJO ,not entire list) to Kafka topic (event hub) . Scheduled a cron job like every hour to send these records(POJO) to event hub.

Able to see messages being sent to eventhub ,but after 3 to 4 successful run getting following exception (which includes several messages being sent and several failing with below exception)
`    Expiring 14 record(s) for eventhubname: 30125  ms has passed since batch creation plus linger time
`
Following is the config for Producer used,

`props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
    props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
    props.put(ProducerConfig.ACKS_CONFIG, "1");
    props.put(ProducerConfig.RETRIES_CONFIG, "3");`

Message Retention period - 7 Partition - 6 
using spring Kafka(2.2.3) to send the events method marked as @Async where kafka send is written
`   @Async
    protected void send() {
       kafkatemplate.send(record);
    }`

## Expected Behavior
1. Message to be sent without any timeout exception 

## Versions  
- Azure Event hub

**Comment by JamesBirdsall** [comment]
This is a Kafka client issue and unrelated to the Java EH client.
