### ISSUE TITLE
Resilience4J

### ISSUE THREAD

**Issue by mohanr** [Azure/azure-event-hubs-java#459]
## Actual Behavior
1. The framework has support for internal retry policies. The policies are not too advanced.

## Expected Behavior
1.  The suggestion is to have a design that enables us to plug Resilience4J into the framework.

**Comment by JamesBirdsall** [comment]
Thanks for bringing this up! The Java event hubs client has moved over to https://github.com/Azure/azure-sdk-for-java where a second-generation client is in the works. If you raise this issue over there with the Event Hubs tag, it is the sort of thing that is being considered for the new client.
