### ISSUE TITLE
Did not observe any item or terminal signal within 4000ms in 'takeUntil'

### ISSUE THREAD

**Issue by fshimamoto** [Azure/azure-event-hubs-java#473]
Hello, we are using the last version of the library azure-messaging-eventhubs.
We only have producers sending data, EH with 20 TU and 32 partitions. We share 1 connection with 30 threads to send data.

**_StackTrace:_**
`java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 4000ms in 'takeUntil' (and no fallback has been configured)","thrown":{"commonElementCount":0,"localizedMessage":"java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 4000ms in 'takeUntil' (and no fallback has been configured)","message":"java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 4000ms in 'takeUntil' (and no fallback has been configured)","name":"reactor.core.Exceptions$ReactiveException","cause":{"commonElementCount":1,"localizedMessage":"Did not observe any item or terminal signal within 4000ms in 'takeUntil' (and no fallback has been configured)","message":"Did not observe any item or terminal signal within 4000ms in 'takeUntil' (and no fallback has been configured)","name":"java.util.concurrent.TimeoutException","extendedStackTrace":"java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 4000ms in 'takeUntil' (and no fallback has been configured)\n\tat reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:289) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]\n\tat reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:274) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]\n\tat reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:396) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]\n\tat reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]\n\tat reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]\n\tat reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]\n\tat reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]\n\tat reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]\n"},"suppressed":[{"commonElementCount":0,"localizedMessage":"#block terminated with an error","message":"#block terminated with an error","name":"java.lang.Exception","extendedStackTrace":"java.lang.Exception: #block terminated with an error\n\tat reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]\n\tat reactor.core.publisher.Mono.block(Mono.java:1666) ~[reactor-core-3.3.4.RELEASE.jar!/:3.3.4.RELEASE]\n\tat com.azure.messaging.eventhubs.EventHubProducerClient.send(EventHubProducerClient.java:192) ~[azure-messaging-eventhubs-5.1.2.jar!/:?]\n\tat com.abinbev.b2b.consumer.service.EventHubService.sendEvent(EventHubService.java:50) `

### Context
OS and version used: Ubuntu
Java runtime used: 11
SDK version used: 5.1.2

**Comment by JamesBirdsall** [comment]
Hello! This is an obsolete repo for the older com.microsoft.azure client. The new com.azure Event Hubs client is maintained over at https://github.com/Azure/azure-sdk-for-java -- if you open this issue there with the "Event Hubs" label, the people who can help you will see it.
