### ISSUE TITLE
EventData constructor hangs

### ISSUE THREAD

**Issue by jayr-davis** [Azure/azure-event-hubs-java#478]
## Actual Behavior
				byte[] payloadBytes = jsonString.getBytes() ;
log.debug("Sending step 1");
				// now that we have the client, send the data
				EventData sendEvent = new EventData(payloadBytes) ;
log.debug("Sending step 2");

When using <azure-messaging-eventhubs.version>5.7.1</azure-messaging-eventhubs.version>, I never see "Sending step 2".

When using <azure-messaging-eventhubs.version>5.4.0</azure-messaging-eventhubs.version>, it works/ it returns.

Change made to pom.xml only and code went BACK to working after pom+code changes caused hang.

## Versions  
OpenJDK 64-Bit Server VM Corretto-8.272.10.3 (build 25.272-b10, mixed mode)
Linux WL-Test-FBP-1c79 5.4.0-1037-aws #39~18.04.1-Ubuntu SMP Fri Jan 15 02:48:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux  (i.e., an AWS box)

REAL cut-n-dry difference.  I note that the constructor has significantly changed.

**Comment by JamesBirdsall** [comment]
Hello! This is a legacy repo which exists to maintain the history of a legacy version of the Java event hubs client. The version you're asking about is maintained over at https://github.com/Azure/azure-sdk-for-java/ -- if you open this issue there with the tag "Event Hubs", the people who can help you will see it.
