### ISSUE TITLE
Logging level not configurable in EPH

### ISSUE THREAD

**Issue by JamesBirdsall** [Azure/azure-event-hubs-java#48]
## Actual Behavior
1. EPH will only ever log SEVERE-level traces and cannot be configured.

## Expected Behavior
1. Logging level can be configured via config file and -Djava.util.logging.config.file=file

## Versions  
- OS platform and version: Windows 10
- Maven package version or commit ID: 0.10.0

This is happening because the code forces the level to SEVERE. That was done because otherwise by default everything INFO and above goes to stderr, which got spammy, and I didn't know that it couldn't be overridden by the config file. One potential approach is to redo the levels so that INFO is not used. WARNING and above occur rarely under normal circumstances and it's OK if they go to stderr by default.

**Comment by jtaubensee** [comment]
Addressed by #60

**Comment by jtaubensee** [comment]
Closing as #60 was merged
