### ISSUE TITLE
Reactor thread is not a deamon thread and remans running after EventHubClient is closed

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs-java#5]
_From @ialexandrov on October 21, 2016 7:19_

There is already an issue about unmanaged threads used in the JavaClient implementation.

java / azure-eventhubs / src / main / java / com / microsoft / azure / servicebus / MessagingFactory.java 

134         final Thread reactorThread = new Thread(new RunReactor(newReactor)); 
135         reactorThread.start(); 

Thread is started and then forgoten.  Later it prevents JVM from exiting.  This is even a bigger issue in the EE environment.
1. Please switch to using ExecutorService
2. Please shutdown the executor upon EventHubClient close

_Copied from original issue: Azure/azure-event-hubs#283_

**Comment by jtaubensee** [comment]
_From @SreeramGarlapati on October 21, 2016 22:14_

@ialexandrov - thanks a lot for filing this issue. I am fixing this... ETA 10/28

**Comment by jtaubensee** [comment]
_From @SreeramGarlapati on October 25, 2016 18:39_

HI @ialexandrov - Thanks a lot for filing the issue. I am working on the
fix.

**Comment by jtaubensee** [comment]
_From @SreeramGarlapati on October 28, 2016 23:51_

HI @ialexandrov - #287 fixes the daemon thread issue. Can you please validate... 

We will start taking ExecutorService in the Client API soon.

**Comment by jtaubensee** [comment]
_From @SreeramGarlapati on October 31, 2016 20:18_

@ialexandrov - we released 0.9.0 - which addresses this issue. give it a try & let us know!

**Comment by ialexandrov** [comment]
Hello Guys,

I have checked the fix.  Works fine now. Thank you.

**Comment by SreeramGarlapati** [comment]
great - Thanks for verifying @ialexandrov.
