### ISSUE TITLE
Service bus exception, onTransportError when connecting to Event Hub

### ISSUE THREAD

**Issue by holidayspirit** [Azure/azure-event-hubs-java#51]
Hello

I'm trying to send a payload to a newly created Azure Event Hub, and I receive this error:

"Feb 07, 2017 10:27:19 AM com.microsoft.azure.servicebus.amqp.ConnectionHandler onTransportError
WARNING: Connection.onTransportError: hostname[myeventhub.servicebus.windows.net:5671], error[connection aborted]
Service bus exception: connection aborted"

(where myeventhub replaces the actual name of my event hub)

My method of setting up and sending to the hub is this:

-------------------------------
```
final String namespaceName = "----ServiceBusNamespaceName-----";
final String eventHubName = "----EventHubName-----";
final String sasKeyName = "-----SharedAccessSignatureKeyName-----";
final String sasKey = "---SharedAccessSignatureKey----";
ConnectionStringBuilder connStr = new ConnectionStringBuilder(namespaceName, eventHubName, sasKeyName, sasKey);

try{
	byte[] payloadBytes = "Test message".getBytes("UTF-8");
	EventData sendEvent = new EventData(payloadBytes);
	EventHubClient ehClient = EventHubClient.createFromConnectionStringSync(connStr.toString());
}
catch(ServiceBusException sbe){
	traceln("Service bus exception: " + sbe.getMessage());
}
catch(UnsupportedEncodingException uee){
	traceln("Unsupported Encoding Exception: " + uee.getMessage());
}
catch(IOException ioe){
	traceln("IO Exception: " + ioe.getMessage());
}
```
--------------------------------

I'm using:
- Windows 7 Enterprise
- Java client
- proton-j-0.15.0.jar, azure.eventhubs-0.10.0.jar, bcp-jdk15on-156.jar

This seems to be similar to this issue:  https://github.com/Azure/azure-event-hubs-java/issues/7

My guess is that this may be a firewall thing, but I really want it not to be.  I'm going to try from outside the firewall another day, but for the moment, I'd really appreciate someone's help on this, either to:

- solve the issue
- suggest ways of handling company firewalls

Many thanks

**Comment by SreeramGarlapati** [comment]
@holidayspirit - did you get a chance to run outside of firewall ?
If firewall is indeed ur issue: allowing outbound connections to 5671 should help.

**Comment by holidayspirit** [comment]
@SreeramGarlapati  Thanks for the reply.  Yes, it was a firewall issue.  We've solved it another way, but if that ends up failing we might try your idea.  Many thanks.
