### ISSUE TITLE
Validating connection string

### ISSUE THREAD

**Issue by lhaiesp** [Azure/azure-event-hubs-java#55]
Right now if we want to validate whether a connection string is valid or not (especially whether the sas token is valid), we need to actually create a receiver, specifying the consumer group, partition id, etc. 

Is there an cleaner way to do the connection string validation?

This might be beyond the java library. Since I didn't find anything in c# as well. Let me know if I should bring this issue to the general repository.

**Comment by JamesBirdsall** [comment]
Short answer: AMQP doesn't provide a way to do the sort of lightweight validation you're looking for.

Long answer: At the AMQP level, the service gets the name of the target entity only when a link is created, after the connection and session layers have already been set up. Every entity can have its own SAS policies and keys, so the service cannot do authentication and authorization, or even determine that the entity doesn't exist, until it gets the entity name. We could conceivably implement a flag on the link attach that would cause the service to do authn and authz but not actually create the link, but it would still be necessary to create the AMQP connection and session layers, and in the happy path there would be two link round trips, one to test the creds and then a second to actually create the link. This is actually less efficient than just trying to create a sender/receiver and letting it throw if there's a problem.

**Comment by lhaiesp** [comment]
I'm ok with actually creating a receiver. The problem is just that I want to avoid creating a consumer group just for validation - I have other clients that use the default consumer group to consume events for all partitions already; if the validation uses the default consumer group then it would either steal a partition away or get stuck.

And my token doesn't necessary have write permission. So I can't create a sender I guess.

Seems like no workaround then?

**Comment by JamesBirdsall** [comment]
Event hubs support up to five receivers per partition on the same consumer group. If you create a non-epoch PartitionReceiver directly on $Default/0, for example, that will have no effect on any other receiver as long as you don't hit the quota of five. If you are doing validation only occasionally and close the receiver immediately, that shouldn't be a problem.

Can you tell us a bit more about your use case for validation?

**Comment by lhaiesp** [comment]
The use case is a bit complex to explain. But essentially we just need multiple connections for the same consumer group, based on our discussion above. 

I just tried this out today and the non-epoch receiver works! Not sure whether it's up to five connections per partition as you said. But definitely more than one. I think previously I thought setting epoch to '0' would be effectively equivalent to non-epoch. Apparently I was wrong. For non-epoch receiver the epoch is simply empty.

I would still prefer a cleaner way for validation, but according to your explanation above it seems like we won't have a solution. I'm fine doing validation by actually creating the non-epoch receivers.

Thanks!
