### ISSUE TITLE
Only a single instance of IEventProcessor gets created?

### ISSUE THREAD

**Issue by aliostad** [Azure/azure-event-hubs-java#56]
After talking to Dan Rosanova and  @jtaubensee, I was asked to created this issue last night - which is also related to #52 that @adriancole created.

Basically, from conversations it seems the design of the EPH focused on creating an instance of `IEventProcessor` impl per partition. But in the tests I have had so far only a single instance gets created. This would mean that any implementation of `IEventProcessor` has to be thread-safe and also have a bearing on the checkpointing.
 
So can you please confirm the instancing policy and thread-safety of `IEventProcessor` implementations?

**Comment by adriancole** [comment]
thanks for raising this and pinging me. I'm muy interested this thread!

**Comment by JamesBirdsall** [comment]
An instance of EventProcessorHost creates an instance of IEventProcessor for every partition that it holds the lease for. A given instance of IEventProcessor is created when the EPH instance gets the lease for a partition and is permanently tied to that partition, being shut down and destroyed if and when the EPH instance loses the lease, or the EPH instance as a whole is shut down.

The loop at PartitionManager.java:423 iterates through all the leases and calls Pump.addPump() for each partition that this EPH instance owns. If there already is a pump for that partition, Pump checks its health and restarts if necessary (Pump.java:42); if there isn't one, it creates a new pump (Pump.java:54). Pump.createNewPump() creates a new instance of EventHubPartitionPump and starts it at Pump.java:60-61. The method startPump() is actually implemented on the parent class PartitionPump, and the processor factory is called to create a new IEventProcessor at PartitionPump.java:52.

**Comment by aliostad** [comment]
Thanks James. 

This does not corroborate with my observations. As I said, constructor of my `IEventProcessor` gets called once. I guess the next step is to have a repro?

**Comment by JamesBirdsall** [comment]
A moment of clarification: what I describe is the behavior of the default IEventProcessorFactory. If you implement your own and call EventProcessorHost.RegisterEventProcessorFactory with it, then any pattern is possible.  A user-implemented factory is free to only ever create one IEventProcessor instance and just dispense that instance whenever it is called to create an event processor. We have heard from customers who are doing exactly that.

I assuming that you are NOT doing a custom factory -- if you were, you'd know why your constructor was being called only once! For the default factory, the behavior is supposed to be as I describe, and if you can repro it failing, we would love to see that and fix it.

Thanks!

**Comment by aliostad** [comment]
Thanks James.

You are absolutely correct. I created a bare-bone example and I can see, as you said, we get an instance per partition.
