### ISSUE TITLE
Timeline of 0.11 release?

### ISSUE THREAD

**Issue by CodingCat** [Azure/azure-event-hubs-java#57]
Hi, I am from HDInsight Spark team and we are building a new connector based on the eventhubs client lib

I'm wondering is there any timeline for the 0.11 release, specifically, when will https://github.com/Azure/azure-event-hubs-java/pull/50 get merged and release?

**Comment by xchen0012** [comment]
Cool! Looks like that they merged the #50 pull request.

Thanks a lot!

**Comment by sjkwak** [comment]
Hi @xchen0012 0.11 will be released this week.
