### ISSUE TITLE
Host should deliver empty list instead of NULL when InvokeProcessorAfterReceiveTimeout is set

### ISSUE THREAD

**Issue by serkantkaraca** [Azure/azure-event-hubs-java#58]
Java client's empty message delivery contract is different than SB client. SB client returns an empty list on timeout where Java returns NULL. Better to make behavior consistent across EH clients.

## Actual Behavior
1. OnEvents delivered with NULL messages on timeout.

## Expected Behavior
1.  OnEvents delivered with empty list.

## Versions  
- OS platform and version: Any
- Maven package version or commit ID: Any

**Comment by jtaubensee** [comment]
Fixed with commit 7b2cdb0499dd7e1747334ba6f17352ebc9621c91 in PR #76
