### ISSUE TITLE
Unable to use custom RetryPolicy

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs-java#6]
_From @nirmalpshah on September 22, 2016 20:39_

I'd like to use a retry policy with some custom settings.  I can create the policy and set it in the ConnectionStringBuilder, but get an error when trying to receive events using EPH.

ConnectionStringBuilder connection = new ConnectionStringBuilder(eventHubConfig.getNamespace(),
                    eventHubConfig.getName(), eventHubConfig.getPolicyName(), eventHubConfig.getPolicyKey());
connection.setRetryPolicy(new RetryExponential(
                    Duration.ofMillis(config.backoffMinMillis()),
                    Duration.ofMillis(config.backoffMaxMillis()),
                    Integer.MAX_VALUE,
                    "retryForever"));
String connectionString = connection.toString();
            client = com.microsoft.azure.eventhubs.EventHubClient.createFromConnectionStringSync(connectionString);

// stack trace
com.microsoft.azure.servicebus.IllegalConnectionStringFormatException: Connection string parameter 'RetryPolicy'='retryForever' is not recognized
    at com.microsoft.azure.servicebus.ConnectionStringBuilder.parseConnectionString(ConnectionStringBuilder.java:384) ~[azure-eventhubs-0.8.2.jar:na]
    at com.microsoft.azure.servicebus.ConnectionStringBuilder.<init>(ConnectionStringBuilder.java:149) ~[azure-eventhubs-0.8.2.jar:na]
    at com.microsoft.azure.eventhubs.EventHubClient.createFromConnectionString(EventHubClient.java:96) ~[azure-eventhubs-0.8.2.jar:na]
    at com.microsoft.azure.eventhubs.EventHubClient.createFromConnectionStringSync(EventHubClient.java:52) ~[azure-eventhubs-0.8.2.jar:na]
...

_Copied from original issue: Azure/azure-event-hubs#266_

**Comment by nirmalpshah** [comment]
Any update on this?

**Comment by JamesBirdsall** [comment]
I am looking at this now.

**Comment by nirmalpshah** [comment]
Any update on this?

**Comment by JamesBirdsall** [comment]
Sorry for the silence. The code is ready -- you can see it in branch javaEPH3 -- and I'm hoping to get it pulled to master this week and then released next week.

**Comment by nirmalpshah** [comment]
Excellent! Thank you very much, this looks like it will work as expected.  If there are snapshot libraries, I can run through additional tests; otherwise I'll wait until the next release.  Thanks again for turning this around.

**Comment by jtaubensee** [comment]
Fixed in PR #36
