### ISSUE TITLE
Bug in PartitonContext.checkpoint(EventData event) method

### ISSUE THREAD

**Issue by adoelger** [Azure/azure-event-hubs-java#61]
## Actual Behavior
The method PartitonContext.checkpoint(EventData event) calls the deprecated method "setOffsetAndSequenceNumber" which makes it impossible to save a checkpoint that is before  "this.sequenceNumber"

## Expected Behavior
Remove call to "setOffsetAndSequenceNumber" in "PartitonContext.checkpoint(EventData event)"

## Versions  
- OS platform and version: Linux
- Maven package version or commit ID: 0.10.0

**Comment by sjkwak** [comment]
Hi @adoelger can you provide some details about your scenario?

**Comment by JamesBirdsall** [comment]
Behavior has changed with PR75.
