### ISSUE TITLE
Not able to push messages to Event Hub

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs-java#62]
_From @vedhera on February 15, 2017 17:4_

Hi,
I am using the following code to send messages to event hub and getting following error:

`com.microsoft.azure.servicebus.ServiceBusException: connection aborted`

```java
package com.adf.eventhub;

import java.io.IOException;
import java.nio.charset.*;
import java.util.*;
import java.util.concurrent.ExecutionException;

import com.microsoft.azure.eventhubs.*;
import com.microsoft.azure.servicebus.*;

public class Send
{
    public static void main(String[] args)
            throws ServiceBusException, ExecutionException, InterruptedException, IOException {
        final String namespaceName = "mcdp-event-hub";
        final String eventHubName = "akhilesh-event-hub";
        final String sasKeyName = "mysendpolicy";
        final String sasKey = "<Key>";
        ConnectionStringBuilder connStr = new ConnectionStringBuilder(namespaceName, eventHubName, sasKeyName, sasKey);


        byte[] payloadBytes = "Test AMQP message from JMS".getBytes("UTF-8");
        EventData sendEvent = new EventData(payloadBytes);

        EventHubClient ehClient = EventHubClient.createFromConnectionStringSync(connStr.toString());
        ehClient.sendSync(sendEvent);
    }

}
```
Kindly suggest what is wrong in my implementation.

_Copied from original issue: Azure/azure-event-hubs#298_

**Comment by jtaubensee** [comment]
_From @vedhera on February 15, 2017 17:10_

I get this error everytime I run the code. Moreover I tried changing the dependency to 0.10.0 but still did not work.

Connection String: Endpoint=amqps://mcdp-event-hub.servicebus.windows.net;EntityPath=akhilesh-event-hub;SharedAccessKeyName=mysendpolicy;SharedAccessKey=<Key>;OperationTimeout=PT1M;RetryPolicy=Default

**Comment by SreeramGarlapati** [comment]
Hello @vedhera, `connection aborted` errors typically indicates an error while trying to connect to your SERVICEBUS EventHubs namespace. You should check that there is <a href="http://stackoverflow.com/questions/40905400/connection-aborted-error-while-trying-to-send-events-to-azure-event-hub-using">no firewall rule blocking port 5671</a> (which is the default AMQP port that the java client uses to connect).
