### ISSUE TITLE
Some Issues when ser/deser EventData

### ISSUE THREAD

**Issue by CodingCat** [Azure/azure-event-hubs-java#70]
## Actual Behavior
1. Sample code: https://github.com/CodingCat/eventhubs-sample-event-producer/blob/master/src/main/scala/com/microsoft/azure/eventhubs/client/example/LoremSer2.scala

This program just serialize EventData and deserialize from the file, it seems that the part of the body data which is beyond 1024 turns to garbage data after deserialization

## Expected Behavior

The expected behavior is to deserialize correctly.....

## Versions  
- OS platform and version: Ubuntu/Linux
- Maven package version or commit ID: maven 3, 
- Client Version: observed in 0.9 but I believe it exists in 0.10 0.11 as well

**Comment by sjkwak** [comment]
fix is checked into dev branch.
