### ISSUE TITLE
EventHubClient.send() returns a result with partition and message position

### ISSUE THREAD

**Issue by DuoyueBa** [Azure/azure-event-hubs-java#87]
## Actual Behavior
1. EventHubClient.send() returns CompletableFuture<Void>. We can not know any information, such as: which partition this event is sent to, message position (offset) in stream.

## Expected Behavior
1. EventHubClient.send() returns a result. We can get some information from this result, such as: which partition this event is sent to, message position (offset) in stream.

## Versions  
- OS platform and version:
- Maven package version or commit ID:

**Comment by jtaubensee** [comment]
@DuoyueBa - In case you are concerned with which parition the message goes to, you can use a [`PartitionSender`](https://github.com/Azure/azure-event-hubs-java/blob/dev/azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/PartitionSender.java) to target a specific partition. 

Can you elaborate on your use case a little bit more, for wanting to know the sequence Id, etc.? Most often the sender / receiver processes are unrelated, and do not need to share context.
