### ISSUE TITLE
Define explicit contracts that needs to run on Reactor Thread & in a specific order

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs-java#9]
_From @SreeramGarlapati on August 30, 2016 22:20_

Best examples for this are:
- CreateConnection should be called only from ScheduleOnReactorThread()
- sender/receiver workItems should be enqueued before invoking any proton code (reactor) - which will ensure the onError event to enact on the enqueued work.

_Copied from original issue: Azure/azure-event-hubs#244_

**Comment by SreeramGarlapati** [comment]
with #217 this is taken care.
