### ISSUE TITLE
Remove Service Bus references

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs-java#95]
At one point, parts of this library were planned to be shared with Service Bus. We have since taken the route of keeping all client libraries separate, hence the new Service Bus library. This issue is to track the removal of Service Bus package names in the following files:

https://github.com/Azure/azure-event-hubs-java/tree/dev/azure-eventhubs/src/main/java/com/microsoft/azure/servicebus

This will be a breaking change, and is scheduled for a 1.0.0 release.

**Comment by Blackbaud-AdiSaraf** [comment]
Do you have any ideas on when the 1.0.0 version will be released? We are writing a library that needs to pull in both the event hub and service bus (new 1.0.0 preview).

**Comment by jtaubensee** [comment]
@Blackbaud-AdiSaraf - We don't have an exact timeline on this, but hopefully in the coming weeks.

**Comment by romitgirdhar** [comment]
Hello, just checking when the fix for this issue will be released? Thanks!

**Comment by SreeramGarlapati** [comment]
@sabeegrewal - is working on this release; will coordinate with him to keep the status posted...
