### ISSUE TITLE
Java class is not able to resolve EventData and EventHubClient

### ISSUE THREAD

**Issue by dripta87** [Azure/azure-event-hubs-java#96]
I am using following code to send data to Azure event hub and EventData and EventHubClient are not getting resolved in the code and the code is not being compiled.

import java.io.IOException;
import java.nio.charset.*;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.ExecutionException;

import com.microsoft.azure.eventhubs.*;
import com.microsoft.azure.servicebus.*;
public class Send {

	public static void main(String[] args) 
			throws ServiceBusException, ExecutionException, InterruptedException, IOException
	{
		// TODO Auto-generated method stub
		final String namespaceName = "ns-1234-dt";
	    final String eventHubName = "evt-12345-dt";
	    final String sasKeyName = "sas-12345-dt";
	    final String sasKey = "<Key>";
	    ConnectionStringBuilder connStr = new ConnectionStringBuilder(namespaceName, eventHubName, sasKeyName, sasKey);
	    byte[] payloadBytes = "Test AMQP message from JMS".getBytes("UTF-8");
	    EventData sendEvent = new EventData(payloadBytes);

	    EventHubClient ehClient = EventHubClient.createFromConnectionStringSync(connStr.toString());
	    ehClient.sendSync(sendEvent);

	}

}

I have added below dependency in pom.xml file while creating Maven project

  	<dependency>
  		<groupId>com.microsoft.azure</groupId>
  		<artifactId>azure-eventhubs</artifactId>
  		<version>0.13.1</version>
  	</dependency>

**Comment by SreeramGarlapati** [comment]
@dripta87 - can you please make sure - you got all basics covered - like setting the jdk to 1.8 and any your build environment/IDE specific issues ?
